"""
Comprehensive Authoritative Administrative Level 2 Catalogue across African Countries.
Normalizes secondary administrative divisions (Districts, Sub-counties, Municipalities,
Departments, Communes, Markaz, Cercles, Zones, etc.) for all 55 African countries where
administrative subdivisions exist.
"""
from typing import Dict, List

AFRICAN_LEVEL2_DATA: Dict[str, Dict[str, List[str]]] = {
    # AGO (18 regions)
    "AGO": {
        'Bengo': ['Caxito', 'Ambriz', 'Bula Atumba', 'Dande', 'Dembos', 'Nambuangongo', 'Pango Aluquém'],
        'Benguela': ['Benguela', 'Baía Farta', 'Balombo', 'Bocoio', 'Caimbambo', 'Catumbela', 'Chongorói', 'Cubal', 'Ganda', 'Lobito'],
        'Bié': ['Cuíto', 'Andulo', 'Camacupa', 'Catabola', 'Chinguar', 'Chitembo', 'Cuemba', 'Cunhinga', 'Nharea'],
        'Cabinda': ['Cabinda', 'Belize', 'Buco-Zau', 'Cacongo'],
        'Cuando Cubango': ['Menongue', 'Calai', 'Cuangar', 'Cuchi', 'Cuito Cuanavale', 'Dirico', 'Mavinga', 'Nancova', 'Rivungo'],
        'Cuanza Norte': ["N'dalatando", 'Cambambe', 'Cazengo', 'Golungo Alto', 'Gonguembo', 'Lucala', 'Quiculungo', 'Samba Caju'],
        'Cuanza Sul': ['Sumbe', 'Amboim', 'Cassongue', 'Cela', 'Conda', 'Ebo', 'Libolo', 'Mussende', 'Porto Amboim', 'Quibala', 'Quilenda', 'Seles'],
        'Cunene': ['Ondjiva', 'Cuanhama', 'Curoca', 'Cuvelai', 'Namacunde', 'Ombadja'],
        'Huambo': ['Huambo', 'Bailundo', 'Caála', 'Catchiungo', 'Chicala-Choloanga', 'Chinjenje', 'Ecunha', 'Londuimbali', 'Longonjo', 'Mungo', 'Ucuma'],
        'Huíla': ['Lubango', 'Caconda', 'Caluquembe', 'Chiange', 'Chibia', 'Chicomba', 'Chipindo', 'Cuvango', 'Humpata', 'Jamba', 'Matala', 'Quilengues', 'Quipungo'],
        'Luanda': ['Luanda', 'Belas', 'Cacuaco', 'Cazenga', 'Icolo e Bengo', 'Quiçama', 'Kilamba Kiaxi', 'Talatona', 'Viana'],
        'Lunda Norte': ['Dundo', 'Cambulo', 'Capenda-Camulemba', 'Caungula', 'Chitato', 'Cuango', 'Cuílo', 'Lubalo', 'Lucapa'],
        'Lunda Sul': ['Saurimo', 'Cacolo', 'Dala', 'Muconda'],
        'Malanje': ['Malanje', 'Cacuso', 'Calandula', 'Cambundi-Catembo', 'Cangandala', 'Caombo', 'Cunda-dia-Baze', 'Luquembo', 'Marimba', 'Massango', 'Mucari', 'Quela', 'Quirima'],
        'Moxico': ['Luena', 'Alto Zambeze', 'Bundas', 'Camanongue', 'Léua', 'Luacano', 'Luau', 'Luchazes'],
        'Namibe': ['Moçâmedes', 'Bibala', 'Camucuio', 'Tômbua', 'Virei'],
        'Uíge': ['Uíge', 'Ambuíla', 'Bembe', 'Buengas', 'Bungo', 'Cangola', 'Damba', 'Maquela do Zombo', 'Milunga', 'Mucaba', 'Negage', 'Puri', 'Quimbele', 'Quitexe', 'Sanza Pombo', 'Songo'],
        'Zaire': ["M'banza-Kongo", 'Cuimba', 'Nóqui', "N'zeto", 'Soyo', 'Tomboco'],
    },

    # BDI (18 regions)
    "BDI": {
        'Bubanza': ['Bubanza', 'Gihanga', 'Musigati', 'Mpanda', 'Rwegura'],
        'Bujumbura Mairie': ['Muha', 'Mukaza', 'Ntahangwa'],
        'Bujumbura Rural': ['Isale', 'Kabezi', 'Kanyosha', 'Mubimbi', 'Mugongomanga', 'Mukike', 'Mutambu', 'Mutimbuzi', 'Nyabiraba'],
        'Bururi': ['Bururi', 'Matana', 'Mugamba', 'Rutovu', 'Songa', 'Vyanda'],
        'Cankuzo': ['Cankuzo', 'Cendajuru', 'Gisagara', 'Kigamba', 'Mishiha'],
        'Cibitoke': ['Rugombo', 'Buganda', 'Bukinanyana', 'Mabayi', 'Mugina', 'Murwi'],
        'Gitega': ['Gitega', 'Bugendana', 'Bukirasazi', 'Buraza', 'Giheta', 'Gishubi', 'Itaba', 'Makebuko', 'Mutaho', 'Ryansoro'],
        'Karuzi': ['Buhiga', 'Bugenyuzi', 'Gihogazi', 'Gitaramuka', 'Mutumba', 'Nyabikere', 'Shombo'],
        'Kayanza': ['Kayanza', 'Butaganzwa', 'Gahombo', 'Gatara', 'Kabarore', 'Matongo', 'Muhanga', 'Muruta', 'Rango'],
        'Kirundo': ['Kirundo', 'Bwambarangwe', 'Busoni', 'Bugabira', 'Gitobe', 'Ntega', 'Vumbi'],
        'Makamba': ['Makamba', 'Kayogoro', 'Kibago', 'Mabanda', 'Nyanza-Lac', 'Vugizo'],
        'Muramvya': ['Muramvya', 'Bukeye', 'Kiganda', 'Mbuye', 'Rutegama'],
        'Muyinga': ['Muyinga', 'Buhinyuza', 'Butihinda', 'Gashoho', 'Gasorwe', 'Giteranyi', 'Mwakiro'],
        'Mwaro': ['Gisozi', 'Bisoro', 'Kayokwe', 'Ndava', 'Nyabihanga', 'Rusaka'],
        'Ngozi': ['Ngozi', 'Busiga', 'Gashikanwa', 'Kiremba', 'Marangara', 'Mwumba', 'Nyamurenza', 'Ruhororo', 'Tangara'],
        'Rumonge': ['Rumonge', 'Bugarama', 'Burambi', 'Buyengero', 'Muhuta'],
        'Rutana': ['Rutana', 'Bukemba', 'Giharo', 'Gitanga', 'Mpinga-Kayove', 'Musongati'],
        'Ruyigi': ['Ruyigi', 'Butaganzwa', 'Butezi', 'Bweru', 'Gisuru', 'Kinyinya', 'Nyabitsinda'],
    },

    # BEN (12 regions)
    "BEN": {
        'Alibori': ['Kandi', 'Banikoara', 'Gogounou', 'Karimama', 'Malanville', 'Ségbana'],
        'Atakora': ['Natitingou', 'Boukoumbé', 'Cobly', 'Kérou', 'Kouandé', 'Matéri', 'Pehunco', 'Tanguiéta', 'Toucountouna'],
        'Atlantique': ['Abomey-Calavi', 'Allada', 'Kpomassè', 'Ouidah', 'Sô-Ava', 'Toffo', 'Tori-Bossito', 'Zè'],
        'Borgou': ['Parakou', 'Bembèrèkè', 'Kalalé', "N'Dali", 'Nikki', 'Pèrèrè', 'Sinendé', 'Tchaourou'],
        'Collines': ['Dassa-Zoumè', 'Bantè', 'Glazoué', 'Ouèssè', 'Savalou', 'Savè'],
        'Couffo': ['Aplahoué', 'Djakotomey', 'Dogbo', 'Klouékanmè', 'Lalo', 'Toviklin'],
        'Donga': ['Djougou', 'Bassila', 'Copargo', 'Ouaké'],
        'Littoral': ['Cotonou'],
        'Mono': ['Lokossa', 'Athiémé', 'Bopa', 'Comè', 'Grand-Popo', 'Houéyogbé'],
        'Ouémé': ['Porto-Novo', 'Adjarra', 'Adjohoun', 'Aguégués', 'Akpro-Missérété', 'Avrankou', 'Bonou', 'Dangbo', 'Sèmè-Kpodji'],
        'Plateau': ['Pobè', 'Adja-Ouèrè', 'Ifangni', 'Kétou', 'Sakété'],
        'Zou': ['Abomey', 'Agbangnizoun', 'Bohicon', 'Covè', 'Djidja', 'Ouinhi', 'Za-Kpota', 'Zagnanado', 'Zogbodomey'],
    },

    # BFA (13 regions)
    "BFA": {
        'Boucle du Mouhoun': ['Balé', 'Banwa', 'Kossi', 'Mouhoun', 'Nayala', 'Sourou'],
        'Cascades': ['Comoé', 'Léraba'],
        'Centre': ['Kadiogo (Ouagadougou)'],
        'Centre-Est': ['Boulgou', 'Koulpélogo', 'Kouritenga'],
        'Centre-Nord': ['Bam', 'Namentenga', 'Sanmatenga'],
        'Centre-Ouest': ['Boulkiemdé', 'Sanguié', 'Sissili', 'Ziro'],
        'Centre-Sud': ['Bazèga', 'Nahouri', 'Zoundwéogo'],
        'Est': ['Gnagna', 'Gourma', 'Komondjari', 'Kompienga', 'Tapoa'],
        'Hauts-Bassins': ['Houet (Bobo-Dioulasso)', 'Kénédougou', 'Tuy'],
        'Nord': ['Loroum', 'Passoré', 'Yatenga', 'Zondoma'],
        'Plateau-Central': ['Ganzourgou', 'Kourwéogo', 'Oubritenga'],
        'Sahel': ['Oudalan', 'Séno', 'Soum', 'Yagha'],
        'Sud-Ouest': ['Bougouriba', 'Ioba', 'Noumbiel', 'Poni'],
    },

    # BWA (17 regions)
    "BWA": {
        'Central': ['Serowe/Palapye', 'Mahalapye', 'Bobonong', 'Boteti', 'Tutume'],
        'Chobe': ['Kasane', 'Pandamatenga', 'Kazungula'],
        'Francistown': ['Francistown City'],
        'Gaborone': ['Gaborone Central', 'Gaborone North', 'Gaborone South'],
        'Ghanzi': ['Ghanzi', 'Charleshill'],
        'Jwaneng': ['Jwaneng Town'],
        'Kgalagadi': ['Tsabong', 'Hukuntsi'],
        'Kgatleng': ['Mochudi', 'Oodi', 'Bokaa'],
        'Kweneng': ['Molepolole', 'Letlhakeng', 'Mogoditshane', 'Thamaga'],
        'Lobatse': ['Lobatse Town'],
        'Ngamiland': ['Maun', 'Ngami', 'Okavango'],
        'North-East': ['Masunga', 'Tati'],
        'Orapa': ['Orapa Town'],
        'Selebi-Phikwe': ['Selebi-Phikwe Town'],
        'South-East': ['Ramotswa', 'Tlokweng'],
        'Southern': ['Kanye', 'Barolong', 'Ngwaketse West'],
        'Sowa': ['Sowa Town'],
    },

    # CAF (19 regions)
    "CAF": {
        'Bamingui-Bangoran': ['Ndélé', 'Bamingui'],
        'Bangui': ['1er Arrondissement', '2ème Arrondissement', '3ème Arrondissement', '4ème Arrondissement', '5ème Arrondissement', '6ème Arrondissement', '7ème Arrondissement', '8ème Arrondissement', 'Bimbo', 'Bégoua'],
        'Basse-Kotto': ['Mobaye', 'Alindao', 'Kembé', 'Mingala', 'Zangba'],
        'Haut-Mbomou': ['Obo', 'Bambouti', 'Djemah', 'Zémio'],
        'Haute-Kotto': ['Bria', 'Ouadda', 'Yalinga'],
        'Kémo': ['Sibut', 'Dekoa', 'Mala', 'Ndjoukou'],
        'Lobaye': ['Mbaïki', 'Boda', 'Boganangone', 'Mongoumba'],
        'Mambéré': ['Carnot', 'Amada-Gaza'],
        'Mambéré-Kadéï': ['Berbérati', 'Carnot', 'Amada-Gaza', 'Dédé-Mokouba', 'Gamboula'],
        'Mbomou': ['Bangassou', 'Bakouma', 'Gambo', 'Rafai', 'Ouango'],
        'Nana-Gébizi': ['Kaga-Bandoro', 'Mbrès'],
        'Nana-Mambéré': ['Bouar', 'Baboua', 'Baoro', 'Abba'],
        "Ombella-M'Poko": ['Bimbo', 'Boali', 'Damara', 'Yaloké', 'Bogangolo'],
        'Ouaka': ['Bambari', 'Grimari', 'Ippy', 'Kouango', 'Bakala'],
        'Ouham': ['Bossangoa', 'Batangafo', 'Bouca', 'Kabo', 'Markounda', 'Nana-Bakassa'],
        'Ouham-Fafa': ['Batangafo', 'Bouca'],
        'Ouham-Pendé': ['Bozoum', 'Paoua', 'Bocaranga', 'Koui', 'Ngaoundaye'],
        'Sangha-Mbaéré': ['Nola', 'Bayanga', 'Bambio'],
        'Vakaga': ['Birao', 'Ouanda Djallé'],
    },

    # CIV (14 regions)
    "CIV": {
        'Abidjan': ['Abidjan', 'Anyama', 'Bingerville', 'Songon'],
        'Bas-Sassandra': ['San-Pédro', 'Sassandra', 'Tabou', 'Soubré', 'Méagui', 'Guéyo'],
        'Comoé': ['Abengourou', 'Agnibilékrou', 'Bettié', 'Aboisso', 'Adiaké', 'Grand-Bassam', 'Tiapoum'],
        'Denguélé': ['Odienné', 'Madinani', 'Gbéléban', 'Minignan', 'Kaniasso'],
        'Gôh-Djiboua': ['Gagnoa', 'Oumé', 'Divo', 'Guitry', 'Lakota'],
        'Lacs': ['Dimbokro', 'Bocanda', 'Kouassi-Kouassikro', 'Toumodi', 'Didiévi', 'Tiébissou', 'Daoukro', "M'Bahiakro", 'Bongouanou', 'Arrah'],
        'Lagunes': ['Dabou', 'Grand-Lahou', 'Jacqueville', 'Agboville', 'Sikensi', 'Tiassalé', 'Taabo', 'Adzopé', 'Akoupé', 'Alépé', 'Yakassé-Attobrou'],
        'Montagnes': ['Man', 'Danané', 'Bangolo', 'Biankouma', 'Kouibly', 'Sipilou', 'Guiglo', 'Bloléquin', 'Duékoué', 'Toulépleu'],
        'Sassandra-Marahoué': ['Daloa', 'Issia', 'Vavoua', 'Zoukougbeu', 'Bouaflé', 'Sinfra', 'Zuénoula'],
        'Savanes': ['Korhogo', 'Ferkessédougou', 'Boundiali', 'Sinématiali', 'Dikodougou', 'Ouangolodougou', 'Kouto', 'Tengréla'],
        'Vallée du Bandama': ['Bouaké', 'Béoumi', 'Botro', 'Sakassou', 'Katiola', 'Dabakala', 'Niakaramandougou'],
        'Woroba': ['Séguéla', 'Mankono', 'Touba', 'Kani', 'Dianra', 'Koro', 'Ouaninou'],
        'Yamoussoukro': ['Yamoussoukro', 'Attiégouakro'],
        'Zanzan': ['Bondoukou', 'Bouna', 'Nassian', 'Sandégué', 'Tanda', 'Transua', 'Koun-Fao', 'Doropo', 'Téhini'],
    },

    # CMR (10 regions)
    "CMR": {
        'Adamaoua': ['Vina (Ngaoundéré)', 'Djérem', 'Faro-et-Déo', 'Mayo-Banyo', 'Mbéré'],
        'Centre': ['Mfoundi (Yaoundé)', 'Haute-Sanaga', 'Lekié', 'Mbam-et-Inoubou', 'Mbam-et-Kim', 'Méfou-et-Afamba', 'Méfou-et-Akono', 'Nyong-et-Kéllé', 'Nyong-et-Mfoumou', "Nyong-et-So'o"],
        'East': ['Lom-et-Djérem (Bertoua)', 'Boumba-et-Ngoko', 'Kadey', 'Haut-Nyong'],
        'Far North': ['Diamaré (Maroua)', 'Logone-et-Chari', 'Mayo-Danay', 'Mayo-Kani', 'Mayo-Sava', 'Mayo-Tsanaga'],
        'Littoral': ['Wouri (Douala)', 'Moungo', 'Nkam', 'Sanaga-Maritime'],
        'North': ['Bénoué (Garoua)', 'Faro', 'Mayo-Louti', 'Mayo-Rey'],
        'North-West': ['Mezam (Bamenda)', 'Boyo', 'Bui', 'Donga-Mantung', 'Menchum', 'Momo', 'Ngo-Ketunjia'],
        'South': ['Mvila (Ebolowa)', 'Dja-et-Lobo', 'Océan (Kribi)', 'Vallée-du-Ntem'],
        'South-West': ['Fako (Buea/Limbe)', 'Koupé-Manengouba', 'Lebialem', 'Manyu', 'Meme', 'Ndian'],
        'West': ['Bamboutos', 'Haut-Nkam', 'Hauts-Plateaux', 'Koung-Khi', 'Ménoua', 'Mifi', 'Ndé', 'Noun'],
    },

    # COD (26 regions)
    "COD": {
        'Bas-Uélé': ['Aketi', 'Ango', 'Bambesa', 'Bondo', 'Buta', 'Poko'],
        'Haut-Katanga': ['Lubumbashi', 'Kipushi', 'Likasi', 'Kasenga', 'Mitwaba', 'Pweto', 'Sakania', 'Kambove'],
        'Haut-Lomami': ['Bukama', 'Kabongo', 'Kamina', 'Kaniama', 'Malemba-Nkulu'],
        'Haut-Uélé': ['Dungu', 'Faradje', 'Niangara', 'Rungu', 'Wamba', 'Watsa', 'Isiro'],
        'Ituri': ['Bunia', 'Aru', 'Djugu', 'Irumu', 'Mahagi', 'Mambasa'],
        'Kasaï': ['Dekese', 'Ilebo', 'Kamonia', 'Luebo', 'Mweka', 'Tshikapa'],
        'Kasaï-Central': ['Kananga', 'Demba', 'Dibaya', 'Dimbelenge', 'Kazumba', 'Luiza'],
        'Kasaï-Oriental': ['Mbuji-Mayi', 'Kabeya-Kamwanga', 'Katanda', 'Lupatapata', 'Miabi', 'Tshilenge'],
        'Kinshasa': ['Bandalungwa', 'Barumbu', 'Bumbu', 'Gombe', 'Kalamu', 'Kasa-Vubu', 'Kimbanseke', 'Kinshasa', 'Kintambo', 'Kisenso', 'Lemba', 'Limete', 'Lingwala', 'Makala', 'Maluku', 'Masina', 'Matete', 'Mont-Ngafula', 'Ndjili', 'Ngaba', 'Ngaliema', 'Ngiri-Ngiri', 'Nsele', 'Selembao'],
        'Kongo Central': ['Matadi', 'Boma', 'Kasangulu', 'Kimvula', 'Lukula', 'Luozi', 'Madimba', 'Mbanza-Ngungu', 'Moanda', 'Seke-Banza', 'Songololo'],
        'Kwango': ['Feshie', 'Kahemba', 'Kasongo-Lunda', 'Kenge', 'Popokabaka'],
        'Kwilu': ['Bandundu', 'Bagata', 'Bulungu', 'Gungu', 'Idiofa', 'Kikwit', 'Masi-Manimba'],
        'Lomami': ['Kabinda', 'Kamiji', 'Lubao', 'Luputa', 'Mwene-Ditu', 'Ngandajika'],
        'Lualaba': ['Kolwezi', 'Dilolo', 'Kapanga', 'Mutshatsha', 'Sandoa', 'Lubudi'],
        'Mai-Ndombe': ['Inongo', 'Bolobo', 'Kiri', 'Kutu', 'Kwamouth', 'Mushie', 'Oshwe', 'Yumbi'],
        'Maniema': ['Kindu', 'Kabambare', 'Kailo', 'Kasongo', 'Kibombo', 'Lubutu', 'Pangi', 'Punia'],
        'Mongala': ['Lisala', 'Bumba', 'Bongandanga'],
        'Nord-Kivu': ['Goma', 'Beni', 'Butembo', 'Lubero', 'Masisi', 'Rutshuru', 'Walikale', 'Nyiragongo'],
        'Nord-Ubangi': ['Gbadolite', 'Bosobolo', 'Businga', 'Mobayi-Mbongo', 'Yakoma'],
        'Sankuru': ['Lusambo', 'Katako-Kombe', 'Kole', 'Lodja', 'Lomela', 'Lubefu'],
        'Sud-Kivu': ['Bukavu', 'Fizi', 'Idjwi', 'Kabare', 'Kalehe', 'Mwenga', 'Shabunda', 'Uvira'],
        'Sud-Ubangi': ['Gemena', 'Budjala', 'Kungu', 'Libenge', 'Zongo'],
        'Tanganyika': ['Kalemie', 'Kabalo', 'Kongolo', 'Manono', 'Moba', 'Nyunzu'],
        'Tshopo': ['Kisangani', 'Bafwasende', 'Banalia', 'Basoko', 'Isangi', 'Opala', 'Ubundu', 'Yahuma'],
        'Tshuapa': ['Boende', 'Befale', 'Bokungu', 'Djolu', 'Ikela', 'Monkoto'],
        'Équateur': ['Bikoro', 'Bolomba', 'Bomongo', 'Ingende', 'Lukolela', 'Mbandaka'],
    },

    # COG (12 regions)
    "COG": {
        'Bouenza': ['Madingou', 'Nkayi', 'Mouyondzi', 'Loudima', 'Kayes', 'Kingoué'],
        'Brazzaville': ['Bacongo', 'Makélékélé', 'Poto-Poto', 'Moungali', 'Ouenzé', 'Talangaï', 'Mfilou', 'Madibou', 'Djiri'],
        'Cuvette': ['Owando', 'Makoua', 'Oyo', 'Boundji', 'Mossaka', 'Okoyo'],
        'Cuvette-Ouest': ['Ewo', 'Kéllé', 'Mbomo', 'Okoyo'],
        'Kouilou': ['Hinda', 'Madingo-Kayes', 'Kakamoéka', 'Mvouti'],
        'Likouala': ['Impfondo', 'Bétou', 'Dongou', 'Enyellé', 'Epéna'],
        'Lékoumou': ['Sibiti', 'Komono', 'Zanaga', 'Bambama'],
        'Niari': ['Dolisie', 'Mossendjo', 'Kibangou', 'Louvakou', 'Makabana'],
        'Plateaux': ['Djambala', 'Gamboma', 'Lékana', 'Ngo', 'Abala'],
        'Pointe-Noire': ['Lumumba', 'Mvoumvou', 'Tié-Tié', 'Loandjili', 'Mongo-Mpoukou', 'Ngoyo'],
        'Pool': ['Kinkala', 'Boko', 'Mindouli', 'Kindamba', 'Mayama', 'Ngabé', 'Ignié'],
        'Sangha': ['Ouesso', 'Mokéko', 'Sembé', 'Souanké', 'Pokola'],
    },

    # COM (3 regions)
    "COM": {
        'Anjouan': ['Mutsamudu', 'Domoni', 'Ouani', 'Sima', 'Jimlimé', 'Moya'],
        'Grande Comore': ['Moroni', 'Bambao', 'Oichili', 'Dimani', 'Itsandra', 'Hamahamet', 'Mbadjini', 'Mitsamiouli'],
        'Mohéli': ['Fomboni', 'Nioumachoua', 'Djando', 'Miringoni'],
    },

    # CPV (22 regions)
    "CPV": {
        'Boa Vista': ['Santa Isabel', 'São João Baptista'],
        'Brava': ['São João Baptista', 'Nossa Senhora do Monte'],
        'Maio': ['Nossa Senhora da Luz'],
        'Mosteiros': ['Nossa Senhora da Ajuda'],
        'Paul': ['Santo António das Pombas'],
        'Porto Novo': ['São João Baptista', 'Santo André'],
        'Praia': ['Nossa Senhora da Graça'],
        'Ribeira Brava': ['Nossa Senhora da Lapa', 'Nossa Senhora do Rosário'],
        'Ribeira Grande': ['Nossa Senhora do Rosário', 'Nossa Senhora do Livramento', 'Santo Crucifixo', 'São Pedro Apóstolo'],
        'Ribeira Grande de Santiago': ['Santíssimo Nome de Jesus', 'São João Baptista'],
        'Sal': ['Nossa Senhora das Dores'],
        'Santa Catarina': ['Santa Catarina'],
        'Santa Catarina do Fogo': ['Santa Catarina do Fogo'],
        'Santa Cruz': ['Santiago Maior'],
        'São Domingos': ['Nossa Senhora da Luz', 'São Nicolau Tolentino'],
        'São Filipe': ['Nossa Senhora da Conceição', 'São Lourenço'],
        'São Lourenço dos Órgãos': ['São Lourenço dos Órgãos'],
        'São Miguel': ['São Miguel Arcanjo'],
        'São Salvador do Mundo': ['São Salvador do Mundo'],
        'São Vicente': ['Nossa Senhora da Luz'],
        'Tarrafal': ['Santo Amaro Abade'],
        'Tarrafal de São Nicolau': ['Sagrado Coração de Jesus'],
    },

    # DJI (6 regions)
    "DJI": {
        'Ali Sabieh': ['Ali Sabieh', 'Holhol', 'Dasbiyo', 'Ali Addeh'],
        'Arta': ['Arta', "We'a", 'Loyada', 'Damerjog'],
        'Dikhil': ['Dikhil', 'As Eyla', 'Yoboki', 'Moulhoule'],
        'Djibouti': ['Ras Dika', 'Boulaos', 'Balbala'],
        'Obock': ['Obock', 'Alaili Dadda', 'Khor Angar'],
        'Tadjourah': ['Tadjourah', 'Randa', 'Dorra', 'Adaillou'],
    },

    # DZA (58 regions)
    "DZA": {
        'Adrar': ['Adrar', 'Aoulef', 'Reggane', 'Timimoun', 'Zaouiet Kounta', 'Tsabit', 'Fenoughil'],
        'Algiers': ["Sidi M'Hamed", 'Bab El Oued', 'Hussein Dey', 'Bouzareah', 'Bir Mourad Raïs', 'El Harrach', 'Dar El Beïda', 'Chéraga', 'Zéralda', 'Draria', 'Birtouta', 'Rouïba', 'Baraki'],
        'Annaba': ['Annaba', 'El Bouni', 'El Hadjar', 'Berrahal', 'Aïn Berda', 'Chetaïbi'],
        'Aïn Defla': ['Aïn Defla', 'Miliana', 'Khemis Miliana', 'El Attaf', 'Djelida', 'Rouina', 'El Abadia', 'Bathia', 'Bordj Emir Khaled'],
        'Aïn Témouchent': ['Aïn Témouchent', 'Béni Saf', 'Hammam Bou Hadjar', 'Aïn El Arbaa', 'El Amria', 'Oulhassa Gheraba', 'El Malah'],
        'Batna': ['Batna', 'Barika', 'Aïn Touta', 'Merouana', 'Tazoult', 'Arris', "N'Gaous", 'Ras El Aioun'],
        'Biskra': ['Biskra', 'Tolga', 'Sidi Okba', 'Zeribet El Oued', 'Foughala', 'El Kantara', 'Ouled Djellal'],
        'Blida': ['Blida', 'Boufarik', 'Bougara', 'Mouzaïa', 'El Affroun', 'Ouled Yaïch', 'Meftah', 'Larbaa'],
        'Bordj Badji Mokhtar': ['Bordj Badji Mokhtar', 'Timiaouine'],
        'Bordj Bou Arréridj': ['Bordj Bou Arréridj', 'Ras El Oued', 'Bordj Ghedir', 'Mansoura', 'Medjana', 'El Hamadia', 'Bir Kasdali'],
        'Bouira': ['Bouira', 'Lakhdaria', 'Sour El Ghouzlane', 'Aïn Bessem', "M'Chedallah", 'Bir Ghbalou', 'Bordj Okhriss', 'Bechloul'],
        'Boumerdès': ['Boumerdès', 'Bordj Ménaïel', 'Dellys', 'Isser', 'Thénia', 'Baghlia', 'Boudouaou', 'Khemis El Khechna'],
        'Béchar': ['Béchar', 'Abadla', 'Béni Abbès', 'Taghit', 'Tabelbala', 'Kenadsa'],
        'Béjaïa': ['Béjaïa', 'Akbou', 'Amizour', 'Seddouk', 'Kherrata', 'Tazmalt', 'Sidi Aïch', 'El Kseur'],
        'Béni Abbès': ['Béni Abbès', 'Kerzaz', 'Tabelbala', 'Ouled Khoudir', 'El Ouata'],
        'Chlef': ['Chlef', 'Abou El Hassan', 'El Karimia', 'Oued Fodda', 'Boukadir', 'Taougrit', 'Ténès', 'Zeboudja'],
        'Constantine': ['Constantine', 'El Khroub', 'Aïn Abid', 'Hamma Bouziane', 'Zighoud Youcef', 'Ibn Ziad'],
        'Djanet': ['Djanet', 'Bordj El Haouas'],
        'Djelfa': ['Djelfa', 'Aïn Oussera', 'Messaad', 'Hassi Bahbah', 'Dar Chioukh', 'Charef', 'El Idrissia', 'Sidi Ladjel'],
        'El Bayadh': ['El Bayadh', 'Rogassa', 'Brezina', 'El Abiodh Sidi Cheikh', 'Bougtob', 'Chellala'],
        "El M'Ghair": ["El M'Ghair", 'Djamaa'],
        'El Meniaa': ['El Meniaa', 'Mansoura'],
        'El Oued': ['El Oued', 'Guémar', 'Reguiba', 'Debila', 'Bayadha', 'Robbah', 'Magrane', 'Hassi Khalifa'],
        'El Tarf': ['El Tarf', 'El Kala', "Ben M'Hidi", 'Bouhadjar', 'Besbes', 'Dréan'],
        'Ghardaïa': ['Ghardaïa', 'El Guerrara', 'Metlili', 'Berriane', 'Bounoura', 'Daya Ben Dahoua', 'Zelfana'],
        'Guelma': ['Guelma', 'Oued Zenati', 'Bouchegouf', 'Héliopolis', 'Guelaât Bou Sbaâ', 'Hammam Debagh'],
        'Illizi': ['Illizi', 'In Amenas'],
        'In Guezzam': ['In Guezzam', 'Tin Zaouatine'],
        'In Salah': ['In Salah', 'In Ghar'],
        'Jijel': ['Jijel', 'El Milia', 'Taher', 'Chekfa', 'El Ancer', 'Texenna', 'Sidi Maarouf', 'Ziama Mansouriah'],
        'Khenchela': ['Khenchela', 'Kaïs', 'Chechar', 'Ouled Rechache', 'Bouhmama', 'Aïn Touila', 'Babar'],
        'Laghouat': ['Laghouat', 'Aflou', 'Ksar El Hirane', 'Sidi Makhlouf', "Hassi R'Mel", 'Aïn Madhi', 'Brida', 'El Ghicha'],
        "M'Sila": ["M'Sila", 'Bou Saâda', 'Sidi Aïssa', 'Aïn El Melh', 'Magra', 'Ben Srour', 'Medjedel', 'Hammam Dhalaa'],
        'Mascara': ['Mascara', 'Mohammadia', 'Sig', 'Tighennif', 'Ghriss', 'Oued El Abtal', 'Aïn Fares', 'Bouhanifia'],
        'Mila': ['Mila', 'Chelghoum Laïd', 'Tadjenanet', 'Grarem Gouga', 'Teleghma', 'Rouached', 'Ferdjioua'],
        'Mostaganem': ['Mostaganem', 'Aïn Tedeles', 'Sidi Lakhdar', 'Hassi Mameche', 'Bouguirat', 'Sidi Ali', 'Mesra'],
        'Médéa': ['Médéa', 'Berrouaghia', 'Ksar Boukhari', 'Béni Slimane', 'Tablat', 'El Omaria', 'Souagui', 'Chahbounia'],
        'Naâma': ['Naâma', 'Mécheria', 'Aïn Séfra', 'Asla', 'Tiout', 'Sfissifa', 'Moghrar'],
        'Oran': ['Oran', 'Aïn El Turk', 'Arzew', 'Bir El Djir', 'Boutlélis', 'Es Senia', 'Gdyel', 'Oued Tlélat'],
        'Ouargla': ['Ouargla', 'Hassi Messaoud', "N'Goussa", 'Sidi Khouiled'],
        'Ouled Djellal': ['Ouled Djellal', 'Sidi Khaled'],
        'Oum El Bouaghi': ['Oum El Bouaghi', 'Aïn Beïda', "Aïn M'lila", 'Meskiana', 'Ksar Sbahi', 'Fkirina', 'Sigus'],
        'Relizane': ['Relizane', 'Oued Rhiou', 'Mazouna', 'Yellel', 'Aïn Tarek', 'Mendes', 'Ammi Moussa', 'Zemmoura'],
        'Saïda': ['Saïda', 'Ouled Brahim', 'Aïn El Hadjar', 'El Hassasna', 'Youb', 'Sidi Boubekeur'],
        'Sidi Bel Abbès': ['Sidi Bel Abbès', 'Telagh', 'Ben Badis', 'Sfisef', 'Tessala', 'Ras El Ma', 'Marhoum', 'Merine'],
        'Skikda': ['Skikda', 'El Hadaiek', 'Collo', 'Azzaba', 'Tamalous', 'Ramdane Djamel', 'Sidi Mezghiche', 'Oum Toub'],
        'Souk Ahras': ['Souk Ahras', 'Sedrata', 'Mechroha', 'Taoura', "M'Daourouch", 'Ouled Driss', 'Bir Bouhouche'],
        'Sétif': ['Sétif', 'El Eulma', 'Aïn Oulmene', 'Aïn Arnat', 'Aïn El Kebira', 'Bougaa', 'Amoucha', 'Beni Aziz'],
        'Tamanrasset': ['Tamanrasset', 'Abalessa', 'Tazrouk'],
        'Tiaret': ['Tiaret', 'Sougueur', 'Frenda', 'Mahdia', 'Ksar Chellala', 'Dahmouni', 'Rahouia', 'Mechraa Sfa'],
        'Timimoun': ['Timimoun', 'Aougrout', 'Charouine', 'Tinerkouk'],
        'Tindouf': ['Tindouf', 'Oum El Assel'],
        'Tipaza': ['Tipaza', 'Cherchell', 'Kolea', 'Bou Ismaïl', 'Hadjout', 'Sidi Amar', 'Gouraya', 'Fouka', 'Damous'],
        'Tissemsilt': ['Tissemsilt', 'Theniet El Had', 'Bordj Bou Naama', 'Lardjem', 'Khemisti', 'Ammari'],
        'Tizi Ouzou': ['Tizi Ouzou', 'Azazga', 'Tigzirt', 'Draâ El Mizan', 'Boghni', 'Larbaâ Nath Irathen', 'Aïn El Hammam', 'Ouadhia'],
        'Tlemcen': ['Tlemcen', 'Mansourah', 'Maghnia', 'Ghazaouet', 'Remchi', 'Sebdou', 'Nedroma', 'Hennaya'],
        'Touggourt': ['Touggourt', 'Taibet', 'Temacine', 'Megarine'],
        'Tébessa': ['Tébessa', 'Bir El Ater', 'Chéria', 'El Aouinet', 'Ouenza', 'El Kouif', 'Morsott', 'Negrine'],
    },

    # EGY (27 regions)
    "EGY": {
        'Alexandria': ['Montaza', 'Raml', 'Sidi Gaber', 'Moharam Bek', 'Attarin', 'Gomrok', 'Labban', 'Manshiya', 'Karmouz', 'Mina El Basal', 'Borg El Arab', 'Agami', 'Dekheila'],
        'Aswan': ['Aswan', 'Kom Ombo', 'Edfu', 'Nasr El Nuba', 'Daraw', 'Abu Simbel'],
        'Asyut': ['Asyut', 'Dayrut', 'Qusiya', 'Manfalut', 'Abnub', 'Fateh', 'Sahil Salim', 'Badari', 'Sidfa', 'Ghanayem'],
        'Beheira': ['Damanhour', 'Kafr El Dawwar', 'Rashid', 'Idku', 'Abu Hummus', 'Hosh Essa', 'Kom Hamada', 'Delengat', 'Wadi El Natrun'],
        'Beni Suef': ['Beni Suef', 'Wasta', 'Nasser', 'Biba', 'Fashn', 'Somasta', 'Ihnasya'],
        'Cairo': ['Nasr City', 'Heliopolis', 'Maadi', 'Zamalek', 'New Cairo', 'El Marg', 'Helwan', 'Shubra', 'El Sayeda Zeinab', 'Mokattam', 'Ain Shams', 'Bulaq', 'El Sahel', 'El Zeitoun', 'Matariya', 'El Salam', 'El Basatin', 'El Tebbin', '15th of May', 'Abdeen', 'Azbakeya'],
        'Dakahlia': ['Mansoura', 'Talkha', 'Mit Ghamr', 'Dikirnis', 'Aga', 'Bilqas', 'Senbelawein', 'Manzala', 'Matariya', 'Shirbin'],
        'Damietta': ['Damietta', 'New Damietta', 'Faraskur', 'Zarqa', 'Kafr Saad', 'Kafr El Battikh', 'Ras El Bar', 'Ezbet El Borg'],
        'Faiyum': ['Fayoum', 'Senuris', 'Ibshaway', 'Itsan', 'Tamiya', 'Yusuf El Seddik'],
        'Gharbia': ['Tanta', 'El Mahalla El Kubra', 'Kafr El Zayat', 'Zifta', 'Samanoud', 'Qutour', 'Basyoun', 'Santa'],
        'Giza': ['Dokki', 'Agouza', 'Imbaba', 'Haram', 'Omrania', 'Bulaq El Dakrour', '6th of October', 'Sheikh Zayed', 'Kerdasa', 'Osseem', 'Hawamdia', 'Badrasheen', 'Ayat', 'Saff', 'Atfih'],
        'Ismailia': ['Ismailia', 'Fayed', 'Qantara Sharq', 'Qantara Gharb', 'Tell El Kebir', 'Abu Suwir', 'Qassasin'],
        'Kafr El Sheikh': ['Kafr El Sheikh', 'Desouk', 'Fuwa', 'Metobas', 'Baltim', 'Hamoul', 'Qallin', 'Sidi Salem', 'Riyadh', 'Beyla'],
        'Luxor': ['Luxor', 'Karnak', 'Armant', 'Esna', 'Qurna', 'Tiba', 'Bayadiya', 'Ziniya'],
        'Matrouh': ['Marsa Matrouh', 'El Alamein', 'Dabaa', 'Siwa', 'Sallum', 'Sidi Barrani', 'Negaila', 'Hamam'],
        'Minya': ['Minya', 'Mallawi', 'Maghagha', 'Bani Mazar', 'Samalut', 'Abu Qurqas', 'Deir Mawas', 'Matai', 'Adwa'],
        'Monufia': ['Shibin El Kom', 'Menouf', 'Ashmoun', 'Sadat City', 'Quesna', 'Berket El Saba', 'Tala', 'El Bagour', 'El Shohada'],
        'New Valley': ['Kharga', 'Dakhla', 'Farafra', 'Baris', 'Balat'],
        'North Sinai': ['Arish', 'Sheikh Zuweid', 'Rafah', 'Bir El Abd', 'Hasana', 'Nakhl'],
        'Port Said': ['Sharq', 'Arab', 'Manakh', 'Dawahy', 'Zohour', 'Gharb', 'Ganoub', 'Port Fouad'],
        'Qalyubia': ['Banha', 'Qalyub', 'Shubra El Kheima', 'Khanka', 'Kafr Shukr', 'Tukh', 'Qaha', 'Shibin El Qanatir'],
        'Qena': ['Qena', 'Nag Hammadi', 'Qus', 'Dishna', 'Farshut', 'Abu Tesht', 'Waqf', 'Naqada', 'Qift'],
        'Red Sea': ['Hurghada', 'Ras Gharib', 'Safaga', 'Quseir', 'Marsa Alam', 'Shalatin', 'Halaib'],
        'Sharqia': ['Zagazig', '10th of Ramadan', 'Belbeis', 'Minya El Qamh', 'Faqous', 'Abu Hammad', 'Hihya', 'Deyarb Negm', 'Kafr Saqr'],
        'Sohag': ['Sohag', 'Akhmim', 'Girga', 'Tahta', 'Balyana', 'Maragha', 'Tama', 'Juhayna', 'Dar El Salam', 'Monshah'],
        'South Sinai': ['Sharm El Sheikh', 'Dahab', 'Nuweiba', 'Taba', 'Saint Catherine', 'Ras Sedr', 'Tor Sinai', 'Abu Rudeis'],
        'Suez': ['Suez', 'Arbaeen', 'Ganayen', 'Faisal', 'Attaka'],
    },

    # ERI (6 regions)
    "ERI": {
        'Anseba': ['Keren', 'Halhal', 'Habero', 'Elabered', 'Geleb', 'Asmat', "Sel'a"],
        'Debub': ['Mendefera', 'Adi Keyh', 'Dekemhare', 'Senafe', 'Segeneiti', 'Mai-Mne', 'Dbarwa', 'Emni Haili'],
        'Gash-Barka': ['Barentu', 'Agordat', 'Tessenei', 'Haikota', 'Shambuko', 'Molki', 'Dghe', 'Gogne'],
        'Maekel': ['Asmara', 'Berikh', 'Ghala Nefhi', 'Semienawi Keih Bahri', 'Debubawi Keih Bahri'],
        'Northern Red Sea': ['Massawa', 'Nakfa', 'Afabet', 'Ghinda', 'Foro', "She'eb"],
        'Southern Red Sea': ['Assab', 'Beylul', 'Tiyo', "Ara'eta"],
    },

    # ESH (5 regions)
    "ESH": {
        'Auserd': ['Bir Enzaran', 'Dougaj', 'Zug', 'Miyek'],
        'Boujdour': ['27 Février', 'Agti', 'Guelta Zemmur'],
        'Dakhla': ['Aargub', 'Bir Gandus', 'Tiniguir'],
        'Es Semara': ['Bir Lehlu', 'Mahbes', 'Tifariti', 'Haouza'],
        'Laayoune': ['Bucraa', 'Dchira', 'Farsia', 'Hagunia'],
    },

    # ETH (14 regions)
    "ETH": {
        'Addis Ababa': ['Bole', 'Kirkos', 'Yeka', 'Arada', 'Gulele', 'Lideta', 'Nifas Silk-Lafto', 'Kolfe Keranio', 'Akaki Kality', 'Addis Ketema', 'Lemi Kura'],
        'Afar': ['Zone 1 (Awsi Rasu)', 'Zone 2 (Kilbet Rasu)', 'Zone 3 (Gabi Rasu)', 'Zone 4 (Fanti Rasu)', 'Zone 5 (Hari Rasu)'],
        'Amhara': ['North Gondar', 'Central Gondar', 'South Gondar', 'West Gondar', 'North Wollo', 'South Wollo', 'North Shewa', 'East Gojjam', 'West Gojjam', 'Awi', 'Wag Hemra', 'Oromia Special Zone'],
        'Benishangul-Gumuz': ['Asosa', 'Metekel', 'Kamashi'],
        'Central Ethiopia': ['Gurage', 'Silte', 'Halaba', 'Hadiya', 'Kembata Tembaro', 'Yem'],
        'Dire Dawa': ['Dire Dawa Urban', 'Gurgura'],
        'Gambela': ['Anuak', 'Nuer', 'Mezhenger', 'Itang'],
        'Harari': ['Harar Urban', 'Harari Rural'],
        'Oromia': ['East Shewa', 'West Shewa', 'North Shewa', 'Jimma', 'Arsi', 'West Arsi', 'Bale', 'Borena', 'Guji', 'East Hararghe', 'West Hararghe', 'Ilu Aba Bora', 'Kelam Welega', 'East Welega', 'West Welega', 'Horo Guduru Welega', 'Buno Bedele', 'West Guji'],
        'Sidama': ['Hawassa', 'Dale', 'Aleta Wondo', 'Shebedino', 'Wensho', 'Bensa', 'Aroresa', 'Hula', 'Dara', 'Boricha'],
        'Somali': ['Fafan', 'Siti', 'Liben', 'Afder', 'Shabele', 'Doolo', 'Korahe', 'Jarar', 'Erer', 'Nogob', 'Daawa'],
        'South Ethiopia': ['Wolayita', 'Gamo', 'Gofa', 'South Omo', 'Konso', 'Derashe', 'Burji', 'Amaro', 'Basketo'],
        "South West Ethiopia Peoples'": ['Keffa', 'Sheka', 'Bench Sheko', 'Dawro', 'West Omo', 'Konta'],
        'Tigray': ['Central Tigray', 'East Tigray', 'North West Tigray', 'South Tigray', 'South East Tigray', 'West Tigray', 'Mekelle Special Zone'],
    },

    # GAB (9 regions)
    "GAB": {
        'Estuaire': ['Libreville', 'Akanda', 'Owendo', 'Ntoum', 'Kango', 'Cocobeach'],
        'Haut-Ogooué': ['Franceville', 'Moanda', 'Mounana', 'Bongoville', 'Okondja', 'Akiéni', 'Bakoumba', 'Leconi'],
        'Moyen-Ogooué': ['Lambaréné', 'Ndjolé'],
        'Ngounié': ['Mouila', 'Ndendé', 'Mandji', 'Fougamou', 'Mbigou', 'Lebamba', 'Mimongo'],
        'Nyanga': ['Tchibanga', 'Mayumba', 'Moabi', 'Mabanda'],
        'Ogooué-Ivindo': ['Makokou', 'Booué', 'Mékambo', 'Ovan'],
        'Ogooué-Lolo': ['Koulamoutou', 'Lastoursville', 'Pana', 'Iboundji'],
        'Ogooué-Maritime': ['Port-Gentil', 'Gamba', 'Omboué'],
        'Woleu-Ntem': ['Oyem', 'Bitam', 'Mitzic', 'Minvoul', 'Medouneu'],
    },

    # GHA (16 regions)
    "GHA": {
        'Ahafo': ['Asunafo North', 'Asunafo South', 'Asutifi North', 'Asutifi South', 'Tano North', 'Tano South'],
        'Ashanti': ['Kumasi Metropolitan', 'Asokore Mampong Municipal', 'Obuasi Municipal', 'Ejisu Municipal', 'Bekwai Municipal', 'Mampong Municipal', 'Atwima Nwabiagya', 'Kwabre East', 'Atwima Kwanwoma', 'Atwima Mponua', 'Amansie Central', 'Amansie West', 'Afigya Kwabre', 'Asante Akim Central', 'Asante Akim North', 'Asante Akim South', 'Offinso Municipal', 'Offinso North', 'Sekyere East', 'Sekyere Central', 'Sekyere South'],
        'Bono': ['Sunyani Municipal', 'Sunyani West', 'Berekum East Municipal', 'Berekum West', 'Dormaa Central Municipal', 'Dormaa East', 'Dormaa West', 'Jaman North', 'Jaman South Municipal', 'Tain', 'Banda', 'Wenchi Municipal'],
        'Bono East': ['Techiman Municipal', 'Techiman North', 'Atebubu-Amantin Municipal', 'Kintampo North Municipal', 'Kintampo South', 'Nkoranza North', 'Nkoranza South Municipal', 'Pru East', 'Pru West', 'Sene East', 'Sene West'],
        'Central': ['Cape Coast Metropolitan', 'Awutu Senya East Municipal', 'Effutu Municipal', 'Komenda-Edina-Eguafo-Abirem Municipal', 'Mfantseman Municipal', 'Agona West Municipal', 'Assin Central Municipal', 'Gomoa East', 'Gomoa Central', 'Gomoa West', 'Abura-Asebu-Kwamankese', 'Twifo Atti-Morkwa', 'Upper Denkyira East Municipal', 'Upper Denkyira West'],
        'Eastern': ['New Juaben South Municipal', 'New Juaben North Municipal', 'Birim Central Municipal', 'Kwahu West Municipal', 'Suhum Municipal', 'Akuapem South', 'Akuapem North Municipal', 'Nsawam Adoagyiri Municipal', 'Abuakwa South Municipal', 'Abuakwa North Municipal', 'Lower Manya Krobo Municipal', 'Yilo Krobo Municipal', 'Asuogyaman', 'Fanteakwa North', 'Fanteakwa South'],
        'Greater Accra': ['Accra Metropolitan', 'Tema Metropolitan', 'Ga Central Municipal', 'Ga East Municipal', 'Ga North Municipal', 'Ga South Municipal', 'Ga West Municipal', 'La Dade Kotopon Municipal', 'Ledzokuku Municipal', 'Krowor Municipal', 'Adentan Municipal', 'Ashaiman Municipal', 'Shai Osudoku', 'Ada East', 'Ada West', 'Ayawaso Central Municipal', 'Ayawaso East Municipal', 'Ayawaso North Municipal', 'Ayawaso West Municipal', 'Ablekuma Central Municipal', 'Ablekuma North Municipal', 'Ablekuma West Municipal', 'Korle Klottey Municipal', 'Okaikwei North Municipal'],
        'North East': ['East Mamprusi Municipal', 'West Mamprusi Municipal', 'Bunkpurugu Nakpanduri', 'Chereponi', 'Mamprugu Moagduri', 'Yunyoo-Nasuan'],
        'Northern': ['Tamale Metropolitan', 'Sagnarigu Municipal', 'Yendi Municipal', 'Savelugu Municipal', 'Nanton', 'Tolon', 'Kumbungu', 'Mion', 'Gushegu Municipal', 'Karaga', 'Tatale Sanguli', 'Zabzugu', 'Kpandai', 'Nanumba North Municipal', 'Nanumba South'],
        'Oti': ['Krachi East Municipal', 'Krachi West', 'Krachi Nchumuru', 'Nkwanta North', 'Nkwanta South Municipal', 'Biakoye', 'Jasikan', 'Kadjebi'],
        'Savannah': ['West Gonja Municipal', 'East Gonja Municipal', 'Central Gonja', 'North Gonja', 'Bole', 'Sawla-Tuna-Kalba', 'North East Gonja'],
        'Upper East': ['Bolgatanga Municipal', 'Bolgatanga East', 'Bawku Municipal', 'Kasena Nankana Municipal', 'Bongo', 'Builsa North Municipal', 'Builsa South', 'Garu', 'Tempane', 'Talensi', 'Nabdam', 'Binduri', 'Pusiga', 'Kasena Nankana West'],
        'Upper West': ['Wa Municipal', 'Wa East', 'Wa West', 'Jirapa Municipal', 'Lawra Municipal', 'Nandom Municipal', 'Nadowli Kaleo', 'Daffiama Bussie Issa', 'Sissala East Municipal', 'Sissala West', 'Lambussie Karni'],
        'Volta': ['Ho Municipal', 'Kpando Municipal', 'Hohoe Municipal', 'South Dayi', 'North Dayi', 'Afadzato South', 'Central Tongu', 'North Tongu', 'South Tongu', 'Ketu South Municipal', 'Ketu North Municipal', 'Keta Municipal', 'Anloga', 'Akatsi South', 'Akatsi North'],
        'Western': ['Sekondi-Takoradi Metropolitan', 'Effia Kwesimintsim Municipal', 'Tarkwa Nsuaem Municipal', 'Prestea Huni-Valley Municipal', 'Ahanta West Municipal', 'Nzema East Municipal', 'Ellembelle', 'Jomoro Municipal', 'Wassa East', 'Wassa Amenfi West Municipal', 'Wassa Amenfi East Municipal', 'Wassa Amenfi Central'],
        'Western North': ['Sefwi Wiawso Municipal', 'Bibiani Anhwiaso Bekwai Municipal', 'Juaboso', 'Bia East', 'Bia West', 'Bodi', 'Suaman', 'Aowin Municipal', 'Akontombra'],
    },

    # GIN (8 regions)
    "GIN": {
        'Boké': ['Boké', 'Boffa', 'Fria', 'Gaoual', 'Koundara'],
        'Conakry': ['Kaloum', 'Dixinn', 'Matam', 'Ratoma', 'Matoto', 'Kassa'],
        'Faranah': ['Faranah', 'Dabola', 'Dinguiraye', 'Kissidougou'],
        'Kankan': ['Kankan', 'Kérouané', 'Kouroussa', 'Mandiana', 'Siguiri'],
        'Kindia': ['Kindia', 'Coyah', 'Dubréka', 'Forécariah', 'Télimélé'],
        'Labé': ['Labé', 'Koubia', 'Lélouma', 'Mali', 'Tougué'],
        'Mamou': ['Mamou', 'Dalaba', 'Pita'],
        'Nzérékoré': ['Nzérékoré', 'Beyla', 'Guéckédou', 'Lola', 'Macenta', 'Yomou'],
    },

    # GMB (6 regions)
    "GMB": {
        'Banjul': ['Banjul', 'Kanifing'],
        'Central River': ['Janjanbureh', 'Fulladu West', 'Niamina Dankunku', 'Niamina East', 'Niamina West', 'Lower Saloum', 'Niani', 'Sami', 'Upper Saloum'],
        'Lower River': ['Mansakonko', 'Jarra Central', 'Jarra East', 'Jarra West', 'Kiang Central', 'Kiang East', 'Kiang West'],
        'North Bank': ['Kerewan', 'Central Baddibu', 'Jokadu', 'Lower Baddibu', 'Lower Niumi', 'Upper Baddibu', 'Upper Niumi'],
        'Upper River': ['Basse', 'Fulladu East', 'Kantora', 'Sandu', 'Wuli East', 'Wuli West'],
        'West Coast': ['Brikama', 'Kombo Central', 'Kombo East', 'Kombo North', 'Kombo South', 'Foni Bintang', 'Foni Bondali', 'Foni Brefet', 'Foni Jarrol', 'Foni Kansala'],
    },

    # GNB (9 regions)
    "GNB": {
        'Bafatá': ['Bafatá', 'Bambadinca', 'Contuboel', 'Galomaro', 'Gamamundo', 'Xitole'],
        'Biombo': ['Quinhámel', 'Prábis', 'Safim'],
        'Bissau': ['Bissau'],
        'Bolama': ['Bolama', 'Bubaque', 'Caravela', 'Uno'],
        'Cacheu': ['Cacheu', 'Caió', 'Canchungo', 'São Domingos'],
        'Gabú': ['Gabú', 'Boé', 'Pitche', 'Pirada', 'Sonaco'],
        'Oio': ['Farim', 'Mansôa', 'Binar', 'Nhacra', 'Bissorã'],
        'Quinara': ['Buba', 'Empada', 'Fulacunda', 'Tite'],
        'Tombali': ['Catió', 'Bedanda', 'Cacine', 'Quebo'],
    },

    # GNQ (8 regions)
    "GNQ": {
        'Annobón': ['San Antonio de Palé'],
        'Bioko Norte': ['Malabo', 'Baney'],
        'Bioko Sur': ['Luba', 'Riaba'],
        'Centro Sur': ['Evinayong', 'Niefang', 'Akurenam'],
        'Djibloho': ['Ciudad de la Paz'],
        'Kié-Ntem': ['Ebebiyín', 'Micomiseng', 'Nsork'],
        'Litoral': ['Bata', 'Mbini', 'Cogo'],
        'Wele-Nzas': ['Mongomo', 'Añisok', 'Nsork'],
    },

    # KEN (47 regions)
    "KEN": {
        'Baringo': ['Baringo Central', 'Baringo North', 'Baringo South', 'Eldama Ravine', 'Mogotio', 'Tiaty'],
        'Bomet': ['Bomet Central', 'Bomet East', 'Chepalungu', 'Konoin', 'Sotik'],
        'Bungoma': ['Bumula', 'Kabuchai', 'Kanduyi', 'Kimilili', 'Mt. Elgon', 'Sirisia', 'Tongaren', 'Webuye East', 'Webuye West'],
        'Busia': ['Budalangi', 'Butula', 'Funyula', 'Matayos', 'Nambale', 'Teso North', 'Teso South'],
        'Elgeyo-Marakwet': ['Keiyo North', 'Keiyo South', 'Marakwet East', 'Marakwet West'],
        'Embu': ['Manyatta', 'Mbeere North', 'Mbeere South', 'Runyenjes'],
        'Garissa': ['Balambala', 'Dadaab', 'Fafi', 'Garissa Township', 'Hulugho', 'Ijara', 'Lagdera'],
        'Homa Bay': ['Homa Bay Town', 'Kabondo Kasipul', 'Karachuonyo', 'Kasipul', 'Mbita', 'Ndhiwa', 'Rangwe', 'Suba'],
        'Isiolo': ['Isiolo North', 'Isiolo South'],
        'Kajiado': ['Kajiado Central', 'Kajiado East', 'Kajiado North', 'Kajiado South', 'Kajiado West'],
        'Kakamega': ['Butere', 'Ikolomani', 'Khwisero', 'Likuyani', 'Lugari', 'Lurambi', 'Malava', 'Matungu', 'Mumias East', 'Mumias West', 'Navakholo', 'Shinyalu'],
        'Kericho': ['Ainamoi', 'Belgut', 'Bureti', 'Kipkelion East', 'Kipkelion West', 'Sigowet-Soin'],
        'Kiambu': ['Gatundu North', 'Gatundu South', 'Githunguri', 'Juja', 'Kabete', 'Kiambaa', 'Kiambu', 'Kikuyu', 'Lari', 'Limuru', 'Ruiru', 'Thika Town'],
        'Kilifi': ['Ganze', 'Kaloleni', 'Kilifi North', 'Kilifi South', 'Magarini', 'Malindi', 'Rabai'],
        'Kirinyaga': ['Gichugu', 'Kirinyaga Central', 'Mwea', 'Ndia'],
        'Kisii': ['Bobasi', 'Bomachoge Borabu', 'Bomachoge Chache', 'Bonchari', 'Kitutu Chache North', 'Kitutu Chache South', 'Nyaribari Chache', 'Nyaribari Masaba', 'South Mugirango'],
        'Kisumu': ['Kisumu Central', 'Kisumu East', 'Kisumu West', 'Muhoroni', 'Nyakach', 'Nyando', 'Seme'],
        'Kitui': ['Kitui Central', 'Kitui East', 'Kitui Rural', 'Kitui South', 'Kitui West', 'Mwingi Central', 'Mwingi North', 'Mwingi West'],
        'Kwale': ['Kinango', 'Lunga Lunga', 'Matuga', 'Msambweni'],
        'Laikipia': ['Laikipia East', 'Laikipia North', 'Laikipia West'],
        'Lamu': ['Lamu East', 'Lamu West'],
        'Machakos': ['Kangundo', 'Kathiani', 'Machakos Town', 'Masinga', 'Matungulu', 'Mavoko', 'Mwala', 'Yatta'],
        'Makueni': ['Kaiti', 'Kibwezi East', 'Kibwezi West', 'Kilome', 'Makueni', 'Mbooni'],
        'Mandera': ['Banissa', 'Lafey', 'Mandera East', 'Mandera North', 'Mandera South', 'Mandera West'],
        'Marsabit': ['Laisamis', 'Moyale', 'North Horr', 'Saku'],
        'Meru': ['Buuri', 'Central Imenti', 'Igembe Central', 'Igembe North', 'Igembe South', 'North Imenti', 'South Imenti', 'Tigania East', 'Tigania West'],
        'Migori': ['Awendo', 'Kuria East', 'Kuria West', 'Nyatike', 'Rongo', 'Suna East', 'Suna West', 'Uriri'],
        'Mombasa': ['Changamwe', 'Jomvu', 'Kisauni', 'Likoni', 'Mvita', 'Nyali'],
        "Murang'a": ['Gatanga', 'Kandara', 'Kangema', 'Kigumo', 'Kiharu', 'Maragua', 'Mathioya'],
        'Nairobi': ['Westlands', 'Dagoretti North', 'Dagoretti South', 'Langata', 'Kibra', 'Roysambu', 'Kasarani', 'Ruaraka', 'Embakasi South', 'Embakasi North', 'Embakasi Central', 'Embakasi East', 'Embakasi West', 'Makadara', 'Kamukunji', 'Starehe', 'Mathare'],
        'Nakuru': ['Bahati', 'Gilgil', 'Kuresoi North', 'Kuresoi South', 'Molo', 'Naivasha', 'Nakuru Town East', 'Nakuru Town West', 'Njoro', 'Rongai', 'Subukia'],
        'Nandi': ['Aldai', 'Chesumei', 'Emgwen', 'Mosop', 'Nandi Hills', 'Tinderet'],
        'Narok': ['Emurua Dikirr', 'Kilgoris', 'Narok East', 'Narok North', 'Narok South', 'Narok West'],
        'Nyamira': ['Borabu', 'Kitutu Masaba', 'North Mugirango', 'West Mugirango'],
        'Nyandarua': ['Kinangop', 'Kipipiri', 'Ndaragwa', 'Ol Joro Orok', 'Ol Kalou'],
        'Nyeri': ['Kieni', 'Mathira', 'Mukurweini', 'Nyeri Town', 'Othaya', 'Tetu'],
        'Samburu': ['Samburu East', 'Samburu North', 'Samburu West'],
        'Siaya': ['Alego Usonga', 'Bondo', 'Gem', 'Rarieda', 'Ugenya', 'Ugunja'],
        'Taita-Taveta': ['Mwatate', 'Taveta', 'Voi', 'Wundanyi'],
        'Tana River': ['Bura', 'Galole', 'Garsen'],
        'Tharaka-Nithi': ["Chuka/Igambang'ombe", 'Maara', 'Tharaka'],
        'Trans Nzoia': ['Cherangany', 'Endebess', 'Kiminini', 'Kwanza', 'Saboti'],
        'Turkana': ['Loima', 'Turkana Central', 'Turkana East', 'Turkana North', 'Turkana South', 'Turkana West'],
        'Uasin Gishu': ['Ainabkoi', 'Kapseret', 'Kesses', 'Moiben', 'Soy', 'Turbo'],
        'Vihiga': ['Emuhaya', 'Hamisi', 'Luanda', 'Sabatia', 'Vihiga'],
        'Wajir': ['Eldas', 'Tarbaj', 'Wajir East', 'Wajir North', 'Wajir South', 'Wajir West'],
        'West Pokot': ['Kacheliba', 'Kapenguria', 'Pokot South', 'Sigor'],
    },

    # LBR (15 regions)
    "LBR": {
        'Bomi': ['Tubmanburg', 'Klay', 'Suehn Mecca', 'Senjeh', 'Dewoin'],
        'Bong': ['Jorquelleh', 'Fuamah', 'Kokoyah', 'Panta', 'Salala', 'Sanoyea', 'Suakoko', 'Zota', 'Kpaai', 'Yeallequellah'],
        'Gbarpolu': ['Bopolu', 'Belleh', 'Bokomu', 'Gounwolaila', 'Kongba'],
        'Grand Bassa': ['Buchanan', 'District 1', 'District 2', 'District 3', 'District 4', 'Owensgrove'],
        'Grand Cape Mount': ['Robertsport', 'Commonwealth', 'Garwula', 'Golakonneh', 'Tewor', 'Porkpa'],
        'Grand Gedeh': ['Zwedru', "B'hai", 'Cavalla', 'Gbao', 'Gbeapo', 'Konobo', 'Putu', 'Tchien'],
        'Grand Kru': ['Barclayville', 'Bleebo', 'Bolloh', 'Buah', 'Dweken', 'Forpoh', 'Garraway', 'Grand Cess', 'Kpi', 'Sasstown'],
        'Lofa': ['Voinjama', 'Foya', 'Kolahun', 'Quardu Gboni', 'Salayea', 'Vahun', 'Zorzor'],
        'Margibi': ['Kakata', 'Gibi', 'Firestone', 'Mambah-Kaba'],
        'Maryland': ['Harper', 'Barrobo', 'Pleebo/Sodeken', 'Karluway'],
        'Montserrado': ['Greater Monrovia', 'Careysburg', 'Commonwealth', 'St. Paul River', 'Todee'],
        'Nimba': ['Sanniquellie-Mah', 'Gbehlay-Geh', 'Zoe-Geh', 'Twan River', 'Yarwein Mehnsonnoh', 'Saclepea-Mah', 'Buu-Yao', 'Boe & Quilla', 'Garr-Bain', 'Kparblee', 'Meinpea-Mahn', 'Wee-Gbe-Hyh', 'Yarpea Mahn', 'Doe'],
        'River Cess': ['Cestos City', 'Beawor', 'Central River Cess', 'Doedain', 'Fen River', 'Jo River', 'Norwein', 'Sam Gbalor'],
        'River Gee': ['Fish Town', 'Chedepo', 'Gbeapo', 'Karforh', 'Nanee', 'Nyenawliken', 'Potupo', 'Sarbo', 'Tuobo'],
        'Sinoe': ['Greenville', 'Butaw', 'Dugbe River', 'Jaedae', 'Juarzon', 'Kpayan', 'Pynes Town', 'Sanquin', 'Tarjuowon'],
    },

    # LBY (22 regions)
    "LBY": {
        'Al Butnan': ['Tobruk', 'Bardia', 'Jaghbub'],
        'Al Jabal al Akhdar': ['Bayda', 'Shahhat', 'Marawa'],
        'Al Jabal al Gharbi': ['Gharyan', 'Yafran', 'Kikla', 'Mizda'],
        'Al Jafara': ['Al-Aziziya', 'Suani', 'Maya'],
        'Al Jufra': ['Hun', 'Waddan', 'Sukna', 'Zillah'],
        'Al Kufra': ['Kufra', 'Tazirbu', 'Rebyana'],
        'Al Marj': ['Al Marj', 'Jardas al Abid', 'Tukra'],
        'Al Murqub': ['Khoms', 'Msallata', 'Tarhuna'],
        'Al Wahat': ['Ajdabiya', 'Jalu', 'Awjila', 'Marada'],
        'An Nuqat al Khams': ['Zuwarah', 'Al-Jmail', 'Regdalin', 'Zultun'],
        'Az Zawiyah': ['Zawiya', 'Sabratha', 'Sorman'],
        'Benghazi': ['Benghazi', 'Al-Kish', 'Berka', 'Salmani', 'Sabri', 'Garyounis'],
        'Derna': ['Darnah', 'Qubbah', 'Al Tamimi'],
        'Ghat': ['Ghat', 'Barkat', 'Al Awaynat'],
        'Misrata': ['Misrata', 'Zliten', 'Bani Walid', 'Qasr Ahmad'],
        'Murzuq': ['Murzuq', 'Qatrun', 'Traghen'],
        'Nalut': ['Nalut', 'Ghadames', 'Wazin', 'Kabaw'],
        'Sabha': ['Sabha', 'Samnu', 'Tamanhint'],
        'Sirte': ['Sirte', 'Harawa', 'Bin Jawad'],
        'Tripoli': ['Tripoli Central', "Souq al-Jum'aa", 'Abu Salim', 'Hay al-Andalus', 'Janzour', 'Tajoura'],
        'Wadi al Hayaa': ['Ubari', 'Al Ghurayfa', 'Bint Baya'],
        'Wadi al Shatii': ['Brak', 'Edri', 'Al-Ghirda'],
    },

    # LSO (10 regions)
    "LSO": {
        'Berea': ['Teyateyaneng', 'Kanana', 'Kueneng', 'Mabote', 'Makeoane', 'Maluba-Lube', 'Mapoteng', 'Motanasela', 'Tebe-Tebe'],
        'Butha-Buthe': ['Butha-Buthe', 'Kao', 'Likila', 'Linakeng', 'Lipelaneng', 'Makhunoane', 'Motete', 'Ntelle', 'Sekhobe', 'Tsime'],
        'Leribe': ['Hlotse', 'Maputsoe', 'Fenyane', 'Hleoheng', 'Kolojane', 'Likila', 'Manka', 'Matlakeng', 'Menkhoaneng', 'Motete', 'Tsikoane'],
        'Mafeteng': ['Mafeteng', 'Koti-Se-Phola', 'Makaota', 'Malakeng', 'Malumeng', "Mamants'o", 'Monyake', 'Ramoetsana', 'Tajane', "Ts'ana-Talana"],
        'Maseru': ['Maseru Urban', 'Machache', 'Makhaleng', 'Maletsunyane', 'Manonyane', 'Matsieng', 'Mazenod', 'Qiloane', 'Rothe', 'Semonkong', 'Thaba-Bosiu'],
        "Mohale's Hoek": ["Mohale's Hoek", 'Khoelenya', 'Likhutloaneng', 'Mashaleng', 'Mootsinyane', 'Nkau', 'Phamong', 'Qabane', 'Siloe', 'Thaba-Mokhele'],
        'Mokhotlong': ['Mokhotlong', 'Bobatsi', 'Khubelu', 'Linakaneng', 'Liphamola', 'Mphokojoane', 'Pae-La-Itlhatsoa', 'Sanqebethu', 'Senqu'],
        "Qacha's Nek": ["Qacha's Nek", "Khomo-Phats'oa", 'Letloepe', 'Macheache', 'Maseepho', 'Thaba-Khubelu', 'White-Hill'],
        'Quthing': ['Moyeni', 'Likhohlong', 'Liphakoe', 'Mphaki', 'Qomoqomong', 'Serutle', 'Tele', 'Tsatsane'],
        'Thaba-Tseka': ['Thaba-Tseka', 'Bokong', 'Khomo-Ea-Mollo', 'Linakeng', 'Monyetleng', 'Rapoleboea', 'Sehonghong', 'Thaba-Chitja'],
    },

    # MAR (12 regions)
    "MAR": {
        'Béni Mellal-Khénifra': ['Béni Mellal', 'Azilal', 'Fquih Ben Salah', 'Khénifra', 'Khouribga'],
        'Casablanca-Settat': ['Casablanca', 'Mohammedia', 'Nouaceur', 'Médiouna', 'Berrechid', 'Benslimane', 'El Jadida', 'Settat', 'Sidi Bennour'],
        'Dakhla-Oued Ed-Dahab': ['Oued Ed-Dahab', 'Aousserd'],
        'Drâa-Tafilalet': ['Errachidia', 'Ouarzazate', 'Midelt', 'Tinghir', 'Zagora'],
        'Fès-Meknès': ['Fès', 'Meknès', 'El Hajeb', 'Ifrane', 'Sefrou', 'Moulay Yaâcoub', 'Boulemane', 'Taounate', 'Taza'],
        'Guelmim-Oued Noun': ['Guelmim', 'Assa-Zag', 'Sidi Ifni', 'Tan-Tan'],
        'Laâyoune-Sakia El Hamra': ['Laâyoune', 'Boujdour', 'Tarfaya', 'Es-Semara'],
        'Marrakech-Safi': ['Marrakech', 'Al Haouz', 'Chichaoua', 'El Kelâa des Sraghna', 'Essaouira', 'Rehamna', 'Safi', 'Youssoufia'],
        'Oriental': ['Oujda-Angad', 'Berkane', 'Driouch', 'Figuig', 'Guercif', 'Jerada', 'Nador', 'Taourirt'],
        'Rabat-Salé-Kénitra': ['Rabat', 'Salé', 'Skhirate-Témara', 'Kénitra', 'Khémisset', 'Sidi Kacem', 'Sidi Slimane'],
        'Souss-Massa': ['Agadir-Ida Ou Tanane', 'Inezgane-Aït Melloul', 'Chtouka-Aït Baha', 'Taroudant', 'Tiznit', 'Tata'],
        'Tanger-Tétouan-Al Hoceïma': ['Tanger-Assilah', 'Tétouan', "M'diq-Fnideq", 'Fahs-Anjra', 'Larache', 'Al Hoceïma', 'Chefchaouen', 'Ouezzane'],
    },

    # MDG (23 regions)
    "MDG": {
        'Alaotra-Mangoro': ['Ambatondrazaka', 'Amparafaravola', 'Andilamena', "Anosibe An'ala", 'Moramanga'],
        "Amoron'i Mania": ['Ambositra', 'Ambatofinandrahana', 'Fandriana', 'Manandriana'],
        'Analamanga': ['Antananarivo-Renivohitra', 'Ambohidratrimo', 'Andramasina', 'Anjozorobe', 'Ankazobe', 'Antananarivo-Atsimondrano', 'Antananarivo-Avaradrano', 'Manjakandriana'],
        'Analanjirofo': ['Fénérive-Est', 'Mananara Nord', 'Maroantsetra', 'Sainte-Marie', 'Soanierana Ivongo', 'Vavatenina'],
        'Androy': ['Ambovombe-Androy', 'Bekily', 'Beloha', 'Tsihombe'],
        'Anosy': ['Taolagnaro', 'Amboasary-Atsimo', 'Betroka'],
        'Atsimo-Andrefana': ['Toliara I', 'Toliara II', 'Ampanihy Ouest', 'Ankazoabo', 'Benenitra', 'Betioky Atsimo', 'Beroroha', 'Morombe', 'Sakaraha'],
        'Atsimo-Atsinanana': ['Farafangana', 'Befotaka', 'Midongy-Atsimo', 'Vangaindrano', 'Vondrozo'],
        'Atsinanana': ['Toamasina I', 'Toamasina II', 'Antanambao Manampotsy', 'Brickaville', 'Mahanoro', 'Marolambo', 'Vatomandry'],
        'Betsiboka': ['Maevatanana', 'Kandreho', 'Tsaratanana'],
        'Boeny': ['Mahajanga I', 'Mahajanga II', 'Ambato-Boeny', 'Mahabo', 'Marovoay', 'Mitsinjo', 'Soalala'],
        'Bongolava': ['Tsiroanomandidy', 'Fenoarivobe'],
        'Diana': ['Antsiranana I', 'Antsiranana II', 'Ambanja', 'Ambilobe', 'Nosy Be'],
        'Fitovinany': ['Manakara', 'Ikongo', 'Vohipeno'],
        'Haute Matsiatra': ['Fianarantsoa', 'Ambalavao', 'Ambohimahasoa', 'Ikalamavony', 'Isandra', 'Lalangina', 'Vohibato'],
        'Ihorombe': ['Ihosy', 'Iakora', 'Ivohibe'],
        'Itasy': ['Miarinarivo', 'Arivonimamo', 'Soavinandriana'],
        'Melaky': ['Maintirano', 'Ambatomainty', 'Antsalova', 'Besalampy', 'Morafenobe'],
        'Menabe': ['Morondava', 'Belo sur Tsiribihina', 'Mahabo', 'Manja', 'Miandrivazo'],
        'Sava': ['Sambava', 'Antalaha', 'Vohemar', 'Andapa'],
        'Sofia': ['Antsohihy', 'Analalava', 'Bealanana', 'Befandriana-Nord', 'Mampikony', 'Mandritsara', 'Port-Bergé'],
        'Vakinankaratra': ['Antsirabe I', 'Antsirabe II', 'Ambatolampy', 'Antanifotsy', 'Betafo', 'Faratsiho', 'Mandoto'],
        'Vatovavy': ['Mananjary', 'Ifanadiana', 'Nosy Varika'],
    },

    # MLI (20 regions)
    "MLI": {
        'Bamako': ['Commune I', 'Commune II', 'Commune III', 'Commune IV', 'Commune V', 'Commune VI'],
        'Bandiagara': ['Bandiagara', 'Bankass', 'Koro'],
        'Bougouni': ['Bougouni', 'Kolondiéba', 'Yanfolila'],
        'Dioïla': ['Dioïla', 'Fana', 'Béléko'],
        'Douentza': ['Douentza', 'Hombori'],
        'Gao': ['Gao', 'Ansongo', 'Bourem', 'Ménaka'],
        'Kayes': ['Kayes', 'Bafoulabé', 'Diéma', 'Kéniéba', 'Kita', 'Nioro du Sahel', 'Yélimané'],
        'Kidal': ['Kidal', 'Abéïbara', 'Tessalit', 'Tin-Essako'],
        'Kita': ['Kita', 'Sagabari', 'Toukoto'],
        'Koulikoro': ['Koulikoro', 'Banamba', 'Dioïla', 'Kangaba', 'Kati', 'Kolokani', 'Nara'],
        'Koutiala': ['Koutiala', "M'Pessoba", 'Yorosso'],
        'Mopti': ['Mopti', 'Bandiagara', 'Bankass', 'Djenné', 'Douentza', 'Koro', 'Ténenkou', 'Youwarou'],
        'Ménaka': ['Ménaka', 'Andéramboukane', 'Inékar', 'Tidermène'],
        'Nioro': ['Nioro du Sahel', 'Diéma', 'Sandaré'],
        'San': ['San', 'Tominian'],
        'Sikasso': ['Sikasso', 'Bougouni', 'Kadiolo', 'Kolondiéba', 'Koutiala', 'Yanfolila', 'Yorosso'],
        'Ségou': ['Ségou', 'Baraouéli', 'Bla', 'Macina', 'Niono', 'San', 'Tominian'],
        'Taoudénit': ['Taoudénit', 'Foum Alba', 'Boï-Ahmed'],
        'Tessalit': ['Tessalit', 'Aguelhok', 'Tin-Essako'],
        'Tombouctou': ['Tombouctou', 'Diré', 'Goundam', 'Gourma-Rharous', 'Niafunké'],
    },

    # MOZ (11 regions)
    "MOZ": {
        'Cabo Delgado': ['Pemba', 'Ancuabe', 'Balama', 'Chiúre', 'Ibo', 'Macomia', 'Mecúfi', 'Meluco', 'Metuge', 'Mocímboa da Praia', 'Montepuez', 'Mueda', 'Muidumbe', 'Namuno', 'Nangade', 'Palma', 'Quissanga'],
        'Gaza': ['Xai-Xai', 'Bilene', 'Chibuto', 'Chicualacuala', 'Chigubo', 'Chókwè', 'Chongoene', 'Guijá', 'Limpopo', 'Mabalane', 'Mandlakazi', 'Mapai', 'Massangena', 'Massingir'],
        'Inhambane': ['Inhambane', 'Maxixe', 'Funhalouro', 'Govuro', 'Homoíne', 'Inharrime', 'Inhassoro', 'Jangamo', 'Mabote', 'Massinga', 'Morrumbene', 'Panda', 'Vilankulo', 'Zavala'],
        'Manica': ['Chimoio', 'Báruè', 'Gondola', 'Guro', 'Macate', 'Machaze', 'Macossa', 'Manica', 'Mossurize', 'Sussundenga', 'Tambara', 'Vanduzi'],
        'Maputo City': ['KaMpfumo', 'KaNlhamankulu', 'KaMaxakeni', 'KaMavota', 'KaMubukwana', 'KaTembe', 'KaNyaka'],
        'Maputo Province': ['Matola', 'Boane', 'Magude', 'Manhiça', 'Marracuene', 'Matutuíne', 'Moamba', 'Namaacha'],
        'Nampula': ['Nampula', 'Angoche', 'Eráti', 'Ilha de Moçambique', 'Lalaua', 'Malema', 'Meconta', 'Mecubúri', 'Memba', 'Mogincual', 'Mogovolas', 'Moma', 'Monapo', 'Mossuril', 'Muecate', 'Murrupula', 'Nacala-Porto', 'Nacala-a-Velha', 'Nacarôa', 'Rapale', 'Ribaue'],
        'Niassa': ['Lichinga', 'Cuamba', 'Chimbonila', 'Lago', 'Majune', 'Mandimba', 'Marrupa', 'Maúa', 'Mavago', 'Mecanhelas', 'Mecula', 'Metarica', 'Muembe', "N'gauma", 'Nipepe', 'Sanga'],
        'Sofala': ['Beira', 'Buzi', 'Caia', 'Chemba', 'Cheringoma', 'Chibabava', 'Dondo', 'Gorongosa', 'Machanga', 'Maringué', 'Marromeu', 'Muanza', 'Nhamatanda'],
        'Tete': ['Tete', 'Angónia', 'Cahora-Bassa', 'Changara', 'Chiuta', 'Chifunde', 'Dôa', 'Macanga', 'Magoé', 'Marara', 'Marávia', 'Moatize', 'Mutarara', 'Tsangano', 'Zumbo'],
        'Zambezia': ['Quelimane', 'Alto Molócue', 'Chinde', 'Gilé', 'Gurué', 'Ile', 'Inhassunge', 'Lugela', 'Maganja da Costa', 'Milange', 'Mocuba', 'Mocubela', 'Molumbo', 'Mopeia', 'Morrumbala', 'Namacurra', 'Namarroi', 'Nicoadala', 'Pebane'],
    },

    # MRT (15 regions)
    "MRT": {
        'Adrar': ['Atar', 'Aoujeft', 'Chinguetti', 'Ouadane'],
        'Assaba': ['Kiffa', 'Barkéol', 'Boumdeid', 'Guerou', 'Kankossa'],
        'Brakna': ['Aleg', 'Bababé', 'Boghé', "M'Bagne", 'Magta-Lahjar'],
        'Dakhlet Nouadhibou': ['Nouadhibou', 'Chami'],
        'Gorgol': ['Kaédi', 'Maghama', "M'Bout", 'Monguel'],
        'Guidimaka': ['Sélibaby', 'Ould Yengé', 'Ghabou'],
        'Hodh Ech Chargui': ['Néma', 'Amourj', 'Bassiknou', 'Djiguenni', 'Oualata', 'Timbedra'],
        'Hodh El Gharbi': ['Ayoun', 'Kobenni', 'Tamchekett', 'Tintane', 'Touil'],
        'Inchiri': ['Akjoujt', 'Benichab'],
        'Nouakchott-Nord': ['Dar-Naim', 'Teyarett', 'Toujouonine'],
        'Nouakchott-Ouest': ['Tevragh-Zeina', 'Ksar', 'Sebkha'],
        'Nouakchott-Sud': ['El Mina', 'Arafat', 'Riyadh'],
        'Tagant': ['Tidjikja', 'Moudjéria', 'Tichit'],
        'Tiris Zemmour': ['Zouérat', "F'dérik", 'Bir Moghrein'],
        'Trarza': ['Rosso', 'Keur Macène', 'Mederdra', 'Ouad Naga', "R'Kiz", 'Boutilimit'],
    },

    # MUS (12 regions)
    "MUS": {
        'Agaléga': ['North Island', 'South Island'],
        'Black River': ['Bambous', 'Flic en Flac', 'Tamarin', 'Case Noyale', 'Le Morne'],
        'Cargados Carajos': ['Saint Brandon'],
        'Flacq': ['Centre de Flacq', 'Bel Air Rivière Sèche', 'Lalmatie', 'Poste de Flacq'],
        'Grand Port': ['Mahébourg', 'Rose Belle', 'Plaine Magnien', 'New Grove'],
        'Moka': ['Saint Pierre', 'Moka', 'Quartier Militaire', 'Dagotière'],
        'Pamplemousses': ['Triolet', 'Pamplemousses', 'Terre Rouge', 'Baie du Tombeau'],
        'Plaines Wilhems': ['Beau Bassin-Rose Hill', 'Curepipe', 'Quatre Bornes', 'Vacoas-Phoenix'],
        'Port Louis': ['Port Louis'],
        'Rivière du Rempart': ['Goodlands', 'Grand Baie', "Poudre d'Or", 'Rivière du Rempart'],
        'Rodrigues': ['Port Mathurin', 'Oyster Bay', 'La Ferme'],
        'Savanne': ['Souillac', 'Chemin Grenier', 'Rivière des Anguilles', 'Surinam'],
    },

    # MWI (29 regions)
    "MWI": {
        'Balaka': ['Balaka', 'Kalembo', 'Nsamala', 'Chanthunya'],
        'Blantyre': ['Blantyre City', 'Chigaru', 'Kapeni', 'Kuntaja', 'Lundu', 'Machinjiri', 'Makata', 'Somba'],
        'Chikwawa': ['Chikwawa', 'Chapananga', 'Kasisi', 'Katunga', 'Lundu', 'Makhuwira', 'Masache', 'Ngabu'],
        'Chiradzulu': ['Chiradzulu', 'Chitera', 'Kadewere', 'Likoswe', 'Mpama', 'Nkalo', 'Onga'],
        'Chitipa': ['Chitipa', 'Kameme', 'Mwaulambya', 'Mwenemisuku', 'Nthalire'],
        'Dedza': ['Dedza', 'Chauma', 'Chilikumwendo', 'Kachere', 'Kamenyagwaza', 'Kaphuka', 'Tambala'],
        'Dowa': ['Dowa', 'Chiwere', 'Chakhaza', 'Dzoole', 'Kayembe', 'Msakambewa'],
        'Karonga': ['Karonga', 'Kilupula', 'Kyungu', 'Mwakaboko', 'Wasambo'],
        'Kasungu': ['Chilowamatambe', 'Chisemphere', 'Kaluluma', 'Kaomba', 'Lukwa', 'Wimbe'],
        'Likoma': ['Likoma', 'Chizumulu'],
        'Lilongwe': ['Lilongwe City', 'Chadza', 'Chitukula', 'Kabudula', 'Kalolo', 'Kalumbu', 'Khongoni', 'Mazengera', 'Mtema', 'Njewa'],
        'Machinga': ['Machinga', 'Chamba', 'Chikweo', 'Liwonde', 'Mlomba', 'Ngokwe', 'Nyambi'],
        'Mangochi': ['Chimwala', 'Chowe', 'Jalasi', 'Katuli', 'Makanjira', 'Namabvi'],
        'Mchinji': ['Mchinji', 'Dambe', 'Kapondo', 'Mavwere', 'Mkanda', 'Mlonyeni', 'Simphasi'],
        'Mulanje': ['Mulanje', 'Chikumbu', 'Mabuka', 'Mthiramanja', 'Ndalama', 'Njema', 'Tombondiya'],
        'Mwanza': ['Mwanza', 'Govati', 'Kanduku', 'Nthache'],
        'Mzimba': ['Chindi', 'Jarvikuba Mthembanji', 'Kampingo Sibande', 'Mabulabo', 'Mtwalo', 'Mzukuzuku'],
        'Mzuzu': ['Mzuzu City'],
        'Neno': ['Neno', 'Chekucheku', 'Dambe', 'Mlauli', 'Symon'],
        'Nkhata Bay': ['Nkhata Bay', 'Boghoyo', 'Fukamapiri', 'Kabunduli', 'Mankhambira', 'Timbiri', 'Mkumbira'],
        'Nkhotakota': ['Nkhotakota', 'Kafuzira', 'Kanyenda', 'Malengachanzi', 'Mwadzama', 'Mwansambo'],
        'Nsanje': ['Nsanje', 'Chimombo', 'Malemia', 'Mbenje', 'Ndamera', 'Nyachikadza', 'Tengani'],
        'Ntcheu': ['Ntcheu', 'Champiti', 'Ganya', 'Goodson', 'Kwataine', 'Makwangwala', 'Masasa', 'Njolomole'],
        'Ntchisi': ['Ntchisi', 'Chilooko', 'Kalumo', 'Kasakula', 'Malenga', 'Nthondo'],
        'Phalombe': ['Phalombe', 'Chiwalo', 'Jenala', 'Kaduya', 'Nazombe'],
        'Rumphi': ['Rumphi', 'Chapinduka', 'Kachulu', 'Mwahenga', 'Mwankhunikira', 'Zolokere'],
        'Salima': ['Kambwiri', 'Khombedza', 'Kuluunda', 'Maganga', 'Mwanza', 'Ndindi'],
        'Thyolo': ['Thyolo', 'Bvumbwe', 'Changata', 'Chimaliro', 'Kapichi', 'Khwethemule', 'Nchilamwera', 'Thomas'],
        'Zomba': ['Zomba City', 'Chikowi', 'Kuntumanji', 'Malemia', 'Mwambo', 'Mlumbe'],
    },

    # NAM (16 regions)
    "NAM": {
        '//Karas': ['Keetmanshoop Urban', 'Keetmanshoop Rural', 'Berseba', 'Karasburg', '!Nami#nus (Lüderitz)', 'Oranjemund'],
        'Erongo': ['Walvis Bay Urban', 'Walvis Bay Rural', 'Swakopmund', 'Arandis', 'Daures', 'Karibib', 'Omaruru'],
        'Hardap': ['Mariental Urban', 'Mariental Rural', 'Gibeon', 'Rehoboth Urban East', 'Rehoboth Urban West', 'Rehoboth Rural', 'Aranos', 'Daweb'],
        'Karas': ['Berseba', 'Karasburg East', 'Karasburg West', 'Keetmanshoop Rural', 'Keetmanshoop Urban', '!Nami#nus (Lüderitz)', 'Oranjemund'],
        'Kavango East': ['Rundu Urban', 'Rundu Rural', 'Mashare', 'Ndiyona', 'Mukwe', 'Ndonga Linena'],
        'Kavango West': ['Nkurenkuru', 'Kapako', 'Mpungu', 'Musese', 'Tondoro', 'Mankumpi', 'Ncamagoro', 'Ncuncuni'],
        'Khomas': ['Windhoek East', 'Windhoek West', 'Windhoek Rural', 'Katutura Central', 'Katutura East', 'Khomasdal', 'Moses Garoeb', 'Samora Machel', 'John Pandeni', 'Tobias Hainyeko'],
        'Kunene': ['Opuwo Urban', 'Opuwo Rural', 'Khorixas', 'Epupa', 'Kamanjab', 'Outjo', 'Sesfontein'],
        'Ohangwena': ['Eenhana', 'Endola', 'Engela', 'Epembe', 'Ohangwena', 'Okongo', 'Omundaungilo', 'Ondobe', 'Ongenga', 'Oshikango'],
        'Omaheke': ['Gobabis', 'Aminuis', 'Epukiro', 'Otjinene', 'Otjombinde', 'Kalahari', 'Okorukambe'],
        'Omusati': ['Outapi', 'Anamulenge', 'Elim', 'Ogongo', 'Okahao', 'Okalongo', 'Onesi', 'Oshikuku', 'Ruacana', 'Tsandi', 'Otamanzi', 'Etayi'],
        'Oshana': ['Oshakati East', 'Oshakati West', 'Ondangwa Urban', 'Ondangwa Rural', 'Ongwediva', 'Okaku', 'Okatyali', 'Ompundja', 'Uuvudhiya', 'Uukwiyu'],
        'Oshikoto': ['Tsumeb', 'Omuthiya', 'Guinas', 'Eengodi', 'Nehale lyaMpingana', 'Okankolo', 'Olukonda', 'Omuntele', 'Onyaanya', 'Oniipa'],
        'Otjozondjupa': ['Otjiwarongo', 'Okahandja', 'Grootfontein', 'Okakarara', 'Omatako', 'Otavi', 'Tsumkwe'],
        'Zambezi': ['Katima Mulilo Urban', 'Katima Mulilo Rural', 'Judea Lyaboloma', 'Kongola', 'Linyanti', 'Sibbinda', 'Kabbe North', 'Kabbe South'],
        'ǃKaras': ['Berseba', 'Karasburg East', 'Karasburg West', 'Keetmanshoop Rural', 'Keetmanshoop Urban', '!Nami#nus (Lüderitz)', 'Oranjemund'],
    },

    # NER (8 regions)
    "NER": {
        'Agadez': ['Arlit', 'Bilma', 'Tchirozérine', 'Iferouane', 'Aderbissinat', 'Bermo'],
        'Diffa': ['Diffa', 'Maïné-Soroa', "N'Guigmi", "N'Gourti", 'Bosso', 'Goudoumaria'],
        'Dosso': ['Dosso', 'Boboye', 'Dogondoutchi', 'Gaya', 'Loga', 'Doutchi', 'Falmey', 'Tibiri', 'Dioundiou'],
        'Maradi': ['Maradi', 'Aguie', 'Dakoro', 'Guidan Roumdji', 'Madarounfa', 'Mayahi', 'Tessaoua', 'Gazaoua'],
        'Niamey': ['Niamey I', 'Niamey II', 'Niamey III', 'Niamey IV', 'Niamey V'],
        'Tahoua': ['Tahoua', 'Abalak', "Birni N'Konni", 'Bouza', 'Illela', 'Keita', 'Madaoua', 'Malbaza', 'Tchin-Tabaraden'],
        'Tillabéri': ['Tillabéri', 'Filingue', 'Kollo', 'Ouallam', 'Say', 'Tera', 'Balleyara', 'Abala', 'Ayorou', 'Banibangou', 'Bankilare', 'Gotheye', 'Torodi'],
        'Zinder': ['Zinder', 'Gouré', 'Magaria', 'Matameye', 'Mirriah', 'Tanout', 'Belbédji', 'Damagaram Takaya', 'Dungass', 'Kantche', 'Takeita', 'Tesker'],
    },

    # RWA (10 regions)
    "RWA": {
        'Eastern': ['Bugesera', 'Gatsibo', 'Kayonza', 'Kirehe', 'Ngoma', 'Nyagatare', 'Rwamagana'],
        'Eastern Province': ['Bugesera', 'Gatsibo', 'Kayonza', 'Kirehe', 'Ngoma', 'Nyagatare', 'Rwamagana'],
        'Kigali': ['Gasabo', 'Kicukiro', 'Nyarugenge'],
        'Kigali City': ['Gasabo', 'Kicukiro', 'Nyarugenge'],
        'Northern': ['Burera', 'Gakenke', 'Gicumbi', 'Musanze', 'Rulindo'],
        'Northern Province': ['Burera', 'Gakenke', 'Gicumbi', 'Musanze', 'Rulindo'],
        'Southern': ['Gisagara', 'Huye', 'Kamonyi', 'Muhanga', 'Nyamagabe', 'Nyanza', 'Nyaruguru', 'Ruhango'],
        'Southern Province': ['Gisagara', 'Huye', 'Kamonyi', 'Muhanga', 'Nyamagabe', 'Nyanza', 'Nyaruguru', 'Ruhango'],
        'Western': ['Karongi', 'Ngororero', 'Nyabihu', 'Nyamasheke', 'Rubavu', 'Rusizi', 'Rutsiro'],
        'Western Province': ['Karongi', 'Ngororero', 'Nyabihu', 'Nyamasheke', 'Rubavu', 'Rusizi', 'Rutsiro'],
    },

    # SDN (19 regions)
    "SDN": {
        'Al Qadarif': ['Al Qadarif', 'Al Fashaga', "Gala'a Al Nahal", 'Al Rahad', 'Al Qureisha', 'Basunda', 'West Galabat', 'Central Galabat'],
        'Blue Nile': ['Ad-Damazin', 'Al Roseires', 'Baw', 'Geissan', 'Kurmuk', 'Tadamon'],
        'Central Darfur': ['Zalingei', 'Azum', 'Mukjar', 'Wadi Salih', 'Bindisi', 'Um Dukhun', 'Nertiti', 'Rokero'],
        'East Darfur': ['Ed Daeen', 'Adila', 'Abu Karinka', 'Bahr el Arab', 'Asalaya', 'Shearia', 'Yassin'],
        'Gedaref': ['Gedaref', 'Al Fushqa', 'Al Galabat Al Gharbyah', 'Al Qureisha', "Gala'a Al Nahal", 'Basundah'],
        'Gezira': ['Wad Madani', 'Al Kamlin', 'Al Hasaheisa', 'Al Managil', 'Janub Al Jazirah', 'Sharq Al Jazirah', 'Um Algura'],
        'Kassala': ['Kassala', 'Halfa Al Jadida', 'Rural Kassala', 'Nahr Atbara', 'Shamal Ad Delta', 'Janub Ad Delta', 'Talkok', 'Wad Al Hilaw'],
        'Khartoum': ['Khartoum', 'Omdurman', 'Khartoum North (Bahri)', 'Sharq El Nil', 'Jebel Awlia', 'Karari', 'Um Badda'],
        'North Darfur': ['Al Fasher', 'Kutum', 'Kabkabiya', 'Mellit', 'Um Kaddada', 'Al Koma', 'Dar El Salam', 'Tawila', 'Saraf Omra'],
        'North Kordofan': ['El Obeid (Sheikan)', 'Bara', 'Um Rawaba', 'En Nuhud', 'Ghebeish', 'Sodari', 'Jabrat al Sheikh', 'Ar Rahad'],
        'Northern': ['Dongola', 'Merowe', 'Wadi Halfa', 'Al Dabbah', 'Al Golid', 'Delgo', 'Al Burgaig'],
        'Red Sea': ['Port Sudan', 'Suakin', 'Sinkat', 'Tokar', 'Haya', 'Halayeb', 'Agig', 'Gunob Awlieb', 'Derudeeb'],
        'River Nile': ['Atbara', 'Ed Damer', 'Shendi', 'Berber', 'Abu Hamad', 'Al Matamma', 'El Buhaira'],
        'Sennar': ['Sennar', 'Sinjah', 'Dinder', 'East Sennar', 'Abu Hujar', 'Dali', 'Mazmum'],
        'South Darfur': ['Nyala', 'Kas', 'Beliel', 'Ed Al Fursan', 'Rehed Al Birdi', 'Tulus', 'Dimsu', 'Kateela', 'Um Dafuq'],
        'South Kordofan': ['Kadugli', 'Dilling', 'Rashad', 'Abu Jibeha', 'Talodi', 'Al Buram', 'Habila', 'Al Reif Al Sharqi', 'Al Abbasiya'],
        'West Darfur': ['Geneina', 'Kulbus', 'Sirba', 'Beida', 'Habila', 'Kereinik', 'Forobaranga'],
        'West Kordofan': ['Al Fula', 'Babanusa', 'Al Meiram', 'Muglad', 'Lagawa', 'En Nuhud', 'Ghebeish', 'Wad Banda'],
        'White Nile': ['Rabak', 'Kosti', 'Al Jebelein', 'Tendalti', 'Um Rimta', 'Al Gitaina', 'Ad Douiem'],
    },

    # SEN (14 regions)
    "SEN": {
        'Dakar': ['Dakar', 'Guédiawaye', 'Pikine', 'Rufisque', 'Keur Massar'],
        'Diourbel': ['Diourbel', 'Bambey', 'Mbacké'],
        'Fatick': ['Fatick', 'Foundiougne', 'Gossas'],
        'Kaffrine': ['Kaffrine', 'Birkilane', 'Koungheul', 'Malem Hodar'],
        'Kaolack': ['Kaolack', 'Guinguinéo', 'Nioro du Rip'],
        'Kolda': ['Kolda', 'Médina Yoro Foulah', 'Vélingara'],
        'Kédougou': ['Kédougou', 'Salémata', 'Saraya'],
        'Louga': ['Louga', 'Kébémer', 'Linguère'],
        'Matam': ['Matam', 'Kanel', 'Ranérou Ferlo'],
        'Saint-Louis': ['Saint-Louis', 'Dagana', 'Podor'],
        'Sédhiou': ['Sédhiou', 'Bounkiling', 'Goudomp'],
        'Tambacounda': ['Tambacounda', 'Bakel', 'Goudiry', 'Koumpentoum'],
        'Thiès': ['Thiès', "M'bour", 'Tivaouane'],
        'Ziguinchor': ['Ziguinchor', 'Bignona', 'Oussouye'],
    },

    # SLE (9 regions)
    "SLE": {
        'Eastern': ['Kailahun', 'Kenema', 'Kono'],
        'Eastern Province': ['Kailahun', 'Kenema', 'Kono'],
        'North Western': ['Kambia', 'Karene', 'Port Loko'],
        'North Western Province': ['Kambia', 'Karene', 'Port Loko'],
        'Northern': ['Bombali', 'Falaba', 'Koinadugu', 'Tonkolili'],
        'Northern Province': ['Bombali', 'Falaba', 'Koinadugu', 'Tonkolili'],
        'Southern': ['Bo', 'Bonthe', 'Moyamba', 'Pujehun'],
        'Southern Province': ['Bo', 'Bonthe', 'Moyamba', 'Pujehun'],
        'Western Area': ['Western Area Urban', 'Western Area Rural'],
    },

    # SOM (8 regions)
    "SOM": {
        'Banaadir': ['Abdiaziz', 'Bondhere', 'Daynile', 'Dharkenley', 'Hamar Jajab', 'Hamar Weyne', 'Hawl Wadag', 'Heliwa', 'Hodan', 'Howlwadag', 'Kahda', 'Karan', 'Shangani', 'Shibis', 'Waberi', 'Wadajir', 'Yaqshid'],
        'Banadir': ['Abdiaziz', 'Bondhere', 'Daynile', 'Dharkenley', 'Hamar Jajab', 'Hamar Weyne', 'Hawl Wadag', 'Heliwa', 'Hodan', 'Howlwadaag', 'Kahda', 'Karan', 'Shangani', 'Shibis', 'Waberi', 'Wadajir', 'Warta Nabada', 'Yaqshid'],
        'Galmudug': ['Dhusamareb', 'Galkayo South', 'Adado', 'Hobyo', 'Harardhere', 'Abudwak'],
        'Hirshabelle': ['Jowhar', 'Beledweyne', "Bal'ad", 'Buloburde', 'Mahas', 'Mataban', 'Warshikh'],
        'Jubaland': ['Kismayo', 'Afmadow', 'Dhobley', 'Luuq', 'Bardhere', 'Doolow', 'El Wak', 'Garbaharey'],
        'Puntland': ['Garowe', 'Bosaso', 'Galkayo North', 'Qardho', 'Burtinle', 'Badhan'],
        'Somaliland': ['Hargeisa', 'Berbera', 'Burao', 'Borama', 'Erigavo', 'Las Anod', 'Gabiley'],
        'South West': ['Baidoa', 'Afgooye', 'Marka', 'Barawe', 'Wanlaweyn', 'Qansax Dheere', 'Dinsor', 'Hudur'],
    },

    # SSD (13 regions)
    "SSD": {
        'Abyei Area': ['Abyei Central', 'Alal', 'Mijak', 'Ameth Aguok'],
        'Central Equatoria': ['Juba', 'Yei', 'Kajo-Keji', 'Lainya', 'Morobo', 'Terekeka'],
        'Eastern Equatoria': ['Torit', 'Magwi', 'Ikotos', 'Kapoeta North', 'Kapoeta South', 'Kapoeta East', 'Budi', 'Lafon'],
        'Jonglei': ['Bor', 'Akobo', 'Ayod', 'Duk', 'Fangak', 'Pigi (Canal)', 'Twic East', 'Uror', 'Nyirol'],
        'Lakes': ['Rumbek Central', 'Rumbek East', 'Rumbek North', 'Cueibet', 'Yirol West', 'Yirol East', 'Awerial', 'Wulu'],
        'Northern Bahr el Ghazal': ['Aweil Centre', 'Aweil East', 'Aweil North', 'Aweil South', 'Aweil West'],
        'Pibor Area': ['Pibor', 'Pochalla', 'Verteth', 'Gumuruk'],
        'Ruweng Area': ['Abiemnom', 'Pariang'],
        'Unity': ['Bentiu (Rubkona)', 'Guit', 'Koch', 'Leer', 'Mayendit', 'Mayom', 'Panyijiar', 'Pariang'],
        'Upper Nile': ['Malakal', 'Renk', 'Baliet', 'Fashoda', 'Manyo', 'Maban', 'Maiwut', 'Luakpiny (Nasir)', 'Longochuk', 'Panyikang', 'Melut', 'Ulang'],
        'Warrap': ['Kuajok (Gogrial West)', 'Gogrial East', 'Tonj North', 'Tonj South', 'Tonj East', 'Twic'],
        'Western Bahr el Ghazal': ['Wau', 'Raja', 'Jur River'],
        'Western Equatoria': ['Yambio', 'Maridi', 'Mundri West', 'Mundri East', 'Ibba', 'Nzara', 'Ezo', 'Nagero', 'Tambura', 'Mvolo'],
    },

    # STP (8 regions)
    "STP": {
        'Cantagalo': ['Santana', 'Ribeira Afonso'],
        'Caué': ['São João dos Angolares', 'Porto Alegre'],
        'Lembá': ['Neves', 'Santa Catarina'],
        'Lobata': ['Guadalupe', 'Conde', 'Santo Amaro'],
        'Mé-Zóchi': ['Trindade', 'Batepá', 'Bombom'],
        'Pagué': ['Santo António', 'Sundey'],
        'Príncipe Autonomous Region': ['Pagué'],
        'Água Grande': ['São Tomé', 'Pantufo', 'Madre de Deus'],
    },

    # SWZ (4 regions)
    "SWZ": {
        'Hhohho': ['Mbabane', 'Piggs Peak', 'Lobamba', 'Madlangempisi', 'Mhlangatane', 'Motshane', 'Ndzingeni', 'Nkhaba', 'Ntfonjeni', 'Timphisini'],
        'Lubombo': ['Siteki', 'Big Bend', 'Dvokodvweni', 'Hlane', 'Lomahasha', 'Lubuli', 'Lugongolweni', 'Matsanjeni North', 'Mhlume', 'Mpholonjeni', 'Nkilongo', 'Siphofaneni', 'Sithobela'],
        'Manzini': ['Manzini', 'Kwaluseni', 'Matsapha', 'Lobamba Lomdzala', 'Ludzeludze', 'Mafutseni', 'Mahlangatsha', 'Mangcongco', 'Mhlambanyatsi', 'Mkhiweni', 'Mtfongwaneni', 'Ngwempisi', 'Nhlambeni'],
        'Shiselweni': ['Nhlangano', 'Gege', 'Hosea', 'Mtsambama', 'Ngudzeni', 'Nkwene', 'Sandleni', 'Shiselweni I', 'Shiselweni II', 'Sigwe', 'Somntongo', 'Zombodze'],
    },

    # SYC (28 regions)
    "SYC": {
        'Anse Boileau': ['Anse Boileau'],
        'Anse Etoile': ['Anse Etoile'],
        'Anse Royale': ['Anse Royale'],
        'Anse aux Pins': ['Anse aux Pins'],
        'Au Cap': ['Au Cap'],
        'Baie Lazare': ['Baie Lazare'],
        'Baie Sainte Anne': ['Baie Sainte Anne'],
        'Beau Vallon': ['Beau Vallon'],
        'Bel Air': ['Bel Air'],
        'Bel Ombre': ['Bel Ombre'],
        'Cascade': ['Cascade'],
        'English River': ['English River'],
        'Glacis': ['Glacis'],
        "Grand'Anse Mahé": ["Grand'Anse Mahé"],
        "Grand'Anse Praslin": ["Grand'Anse Praslin"],
        'La Digue': ['La Digue'],
        'La Rivière Anglaise': ['English River'],
        'Les Mamelles': ['Les Mamelles'],
        'Mont Buxton': ['Mont Buxton'],
        'Mont Fleuri': ['Mont Fleuri'],
        'Outer Islands': ['Alphonse', 'Amirantes', 'Farquhar', 'Aldabra', 'Southern Coral Group'],
        'Plaiasance': ['Plaisance'],
        'Plaisance': ['Plaisance'],
        'Pointe La Rue': ['Pointe La Rue'],
        'Port Glaud': ['Port Glaud'],
        'Roche Caiman': ['Roche Caiman'],
        'Saint Louis': ['Saint Louis'],
        'Takamaka': ['Takamaka'],
    },

    # TCD (23 regions)
    "TCD": {
        'Bahr el Gazel': ['Bahr el Gazel Nord', 'Bahr el Gazel Sud', 'Bahr el Gazel Ouest'],
        'Batha': ['Batha Est', 'Batha Ouest', 'Fitri'],
        'Borkou': ['Borkou', 'Borkou Yala'],
        'Chari-Baguirmi': ['Baguirmi', 'Chari', 'Loug Chari'],
        'Ennedi-Est': ['Am-Djarass', 'Wadi Hawar'],
        'Ennedi-Ouest': ['Fada', 'Mourtcha'],
        'Guéra': ['Guéra', 'Abtouyour', 'Barh Signaka', 'Mangalmé'],
        'Hadjer-Lamis': ['Dababa', 'Dagana', 'Haraze Al Biar'],
        'Kanem': ['Kanem', 'Nord Kanem', 'Wadi Bissam'],
        'Lac': ['Fouli', 'Kaya', 'Mamdi', 'Wayi'],
        'Logone Occidental': ['Dodjé', 'Lac Wey', 'Ngourkosso', 'Guéni'],
        'Logone Oriental': ['La Nya', 'La Nya Pendé', 'La Pendé', 'Monts de Lam', 'Nya Pendé', 'Kouh-Est', 'Kouh-Ouest'],
        'Mandoul': ['Mandoul Occidental', 'Mandoul Oriental', 'Barh Sara'],
        'Mayo-Kebbi Est': ['Mayo-Boneye', 'Kabbia', "Mont d'Illi", 'Mayo-Lémié'],
        'Mayo-Kebbi Ouest': ['Mayo-Dallah', 'Lac Léré'],
        'Moyen-Chari': ['Barh Kôh', 'Grande Sido', 'Lac Iro'],
        "N'Djamena": ['1er Arrondissement', '2ème Arrondissement', '3ème Arrondissement', '4ème Arrondissement', '5ème Arrondissement', '6ème Arrondissement', '7ème Arrondissement', '8ème Arrondissement', '9ème Arrondissement', '10ème Arrondissement'],
        'Ouaddaï': ['Abdi', 'Assoungha', 'Ouara'],
        'Salamat': ['Aboudeïa', 'Barh Azoum', 'Haraze-Mangueigne'],
        'Sila': ['Djourf Al Ahmar', 'Kimiti'],
        'Tandjilé': ['Tandjilé Est', 'Tandjilé Ouest', 'Tandjilé Centre'],
        'Tibesti': ['Tibesti Est', 'Tibesti Ouest'],
        'Wadi Fira': ['Biltine', 'Dar Tama', 'Iriba', 'Mégri'],
    },

    # TGO (5 regions)
    "TGO": {
        'Centrale': ['Tchaoudjo (Sokodé)', 'Blitta', 'Mô', 'Sotouboua'],
        'Kara': ['Kozah (Kara)', 'Assoli', 'Bassar', 'Binah', 'Dankpen', 'Doufelgou', 'Kéran'],
        'Maritime': ['Golfe (Lomé)', 'Agoè-Nyivé', 'Avé', 'Bas-Mono', 'Lacs', 'Vo', 'Yoto', 'Zio'],
        'Plateaux': ['Ogou (Atakpamé)', 'Agou', 'Amou', 'Anié', 'Danyi', 'Est-Mono', 'Haho', 'Kloto', 'Kpélé', 'Moyen-Mono', 'Wawa'],
        'Savanes': ['Tône (Dapaong)', 'Cinkassé', 'Kpendjal', 'Kpendjal-Ouest', 'Oti', 'Oti-Sud', 'Tandjouaré'],
    },

    # TUN (24 regions)
    "TUN": {
        'Ariana': ['Ariana Ville', 'Ettadhamen', 'Kalâat el-Andalous', 'La Soukra', 'Mnihla', 'Raoued', 'Sidi Thabet'],
        'Ben Arous': ['Ben Arous', 'Bou Mhel el-Bassatine', 'El Mourouj', 'Ezzahra', 'Hammam Chott', 'Hammam Lif', 'Megrine', 'Mohamedia', 'Mornag', 'Radès'],
        'Bizerte': ['Bizerte Nord', 'Bizerte Sud', 'Menzel Bourguiba', 'Mateur', 'Ras Jebel', 'Tinja', 'Ghar El Melh', 'Sejenane'],
        'Béja': ['Béja Nord', 'Béja Sud', 'Medjez el-Bab', 'Testour', 'Téboursouk', 'Nefza', 'Amdoun'],
        'Gabès': ['Gabès Ville', 'Gabès Ouest', 'Gabès Sud', 'Ghannouch', 'El Hamma', 'Matmata', 'Mareth', 'Métouia'],
        'Gafsa': ['Gafsa Ville', 'Gafsa Sud', 'Metlaoui', 'Redeyef', 'Moularès', 'Mdhilla', 'El Ksar', 'Sened'],
        'Jendouba': ['Jendouba', 'Tabarka', 'Ain Draham', 'Fernana', 'Ghardimaou', 'Bou Salem', 'Oued Meliz'],
        'Kairouan': ['Kairouan Nord', 'Kairouan Sud', 'Bou Hajla', 'Chebika', 'Haffouz', 'Nasrallah', 'Oueslatia', 'Sbikha'],
        'Kasserine': ['Kasserine Nord', 'Kasserine Sud', 'Sbeitla', 'Fériana', 'Thala', 'Haidra', 'Foussana', 'Sbiba'],
        'Kebili': ['Kebili Nord', 'Kebili Sud', 'Douz Nord', 'Douz Sud', 'Souk Lahad', 'Faouar'],
        'Kef': ['Kef Est', 'Kef Ouest', 'Dahmani', 'Tajerouine', 'Sakiet Sidi Youssef', 'Kalaat Senan', 'Nebeur'],
        'Mahdia': ['Mahdia', 'Rejiche', 'Ksour Essef', 'El Jem', 'Chebba', 'Melloulèche', 'Sidi Alouane', 'Bou Merdes'],
        'Manouba': ['Manouba', 'Den Den', 'Douar Hicher', 'Oued Ellil', 'Mornaguia', 'Borj El Amri', 'Djedeida', 'Tebourba'],
        'Medenine': ['Medenine Nord', 'Medenine Sud', 'Djerba Houmt Souk', 'Djerba Midoun', 'Djerba Ajim', 'Zarzis', 'Ben Gardane'],
        'Monastir': ['Monastir', 'Moknine', 'Ksar Hellal', 'Téboulba', 'Sahline', 'Bembla', 'Jemmal', 'Bekalta', 'Sayada'],
        'Nabeul': ['Nabeul', 'Hammamet', 'Dar Chaâbane', 'Beni Khiar', 'Korba', 'Menzel Temime', 'Kelibia', 'Grombalia', 'Soliman'],
        'Sfax': ['Sfax Ville', 'Sfax Ouest', 'Sfax Sud', 'Sakiet Ezzit', 'Sakiet Eddaïer', 'Thyna', 'Agareb', 'Jebiniana', 'El Hencha', 'Mahres'],
        'Sidi Bouzid': ['Sidi Bouzid Est', 'Sidi Bouzid Ouest', 'Regueb', 'Menzel Bouzaiane', 'Bir El Hafey', 'Jilma', 'Cebbala'],
        'Siliana': ['Siliana Nord', 'Siliana Sud', 'Makthar', 'Bou Arada', 'Gaâfour', 'El Krib', 'Rouhia', 'Bargou'],
        'Sousse': ['Sousse Ville', 'Sousse Medina', 'Sousse Riadh', 'Hammam Sousse', 'Msaken', 'Kalâa Kebira', 'Kalâa Seghira', 'Enfidha', 'Akouda'],
        'Tataouine': ['Tataouine Nord', 'Tataouine Sud', 'Ghomrassen', 'Remada', 'Dehiba', 'Bir Lahmar', 'Smâr'],
        'Tozeur': ['Tozeur', 'Degache', 'Nefta', 'Tameghza', 'Hazoua'],
        'Tunis': ['Tunis Ville', 'Bab Bhar', 'Bab Souika', 'Carthage', 'La Goulette', 'La Marsa', 'Le Bardo', 'Sidi Bou Said', 'El Menzah', 'El Mourouj'],
        'Zaghouan': ['Zaghouan', 'Zriba', 'Bir Mcherga', 'El Fahs', 'Nadhour', 'Saouaf'],
    },

    # TZA (31 regions)
    "TZA": {
        'Arusha': ['Arusha City', 'Arusha Rural', 'Karatu', 'Longido', 'Meru', 'Monduli', 'Ngorongoro'],
        'Dar es Salaam': ['Ilala', 'Kinondoni', 'Temeke', 'Kigamboni', 'Ubungo'],
        'Dodoma': ['Dodoma Municipal', 'Bahi', 'Chamwino', 'Chemba', 'Kondoa', 'Kongwa', 'Mpwapwa'],
        'Geita': ['Geita', 'Bukombe', 'Chato', 'Mbogwe', "Nyang'hwale"],
        'Iringa': ['Iringa Municipal', 'Iringa Rural', 'Kilolo', 'Mufindi'],
        'Kagera': ['Bukoba Municipal', 'Bukoba Rural', 'Biharamulo', 'Karagwe', 'Kyerwa', 'Missenyi', 'Muleba', 'Ngara'],
        'Katavi': ['Mpanda', 'Mlele', 'Tanganyika'],
        'Kigoma': ['Kigoma-Ujiji', 'Kigoma Rural', 'Buhigwe', 'Kakonko', 'Kasulu', 'Kibondo', 'Uvinza'],
        'Kilimanjaro': ['Moshi Municipal', 'Moshi Rural', 'Hai', 'Mwanga', 'Rombo', 'Same', 'Siha'],
        'Lindi': ['Lindi Municipal', 'Kilwa', 'Liwale', 'Nachingwea', 'Ruangwa'],
        'Manyara': ['Babati', 'Hanang', 'Kiteto', 'Mbulu', 'Simanjiro'],
        'Mara': ['Musoma Municipal', 'Musoma Rural', 'Bunda', 'Butiama', 'Rorya', 'Serengeti', 'Tarime'],
        'Mbeya': ['Mbeya City', 'Mbeya Rural', 'Chunya', 'Kyela', 'Mbarali', 'Rungwe'],
        'Morogoro': ['Morogoro Municipal', 'Morogoro Rural', 'Gairo', 'Kilombero', 'Kilosa', 'Mlimba', 'Malinyi', 'Ulanga'],
        'Mtwara': ['Mtwara Municipal', 'Masasi', 'Nanyamba', 'Nanyumbu', 'Newala', 'Tandahimba'],
        'Mwanza': ['Ilemela', 'Nyamagana', 'Kwimba', 'Magu', 'Misungwi', 'Sengerema', 'Ukerewe'],
        'Njombe': ['Njombe', 'Ludewa', 'Makambako', 'Makete', "Wanging'ombe"],
        'Pemba North': ['Micheweni', 'Wete'],
        'Pemba South': ['Chake Chake', 'Mkoani'],
        'Pwani': ['Bagamoyo', 'Chalinze', 'Kibaha', 'Kibiti', 'Kisarawe', 'Mafia', 'Mkuranga', 'Rufiji'],
        'Rukwa': ['Sumbawanga', 'Kalambo', 'Nkasi'],
        'Ruvuma': ['Songea', 'Mbinga', 'Namtumbo', 'Nyasa', 'Tunduru'],
        'Shinyanga': ['Shinyanga Municipal', 'Shinyanga Rural', 'Kahama', 'Kishapu', 'Msalala', 'Ushetu'],
        'Simiyu': ['Bariadi', 'Busega', 'Itilima', 'Maswa', 'Meatu'],
        'Singida': ['Singida Municipal', 'Singida Rural', 'Iramba', 'Ikungi', 'Manyoni', 'Mkalama'],
        'Songwe': ['Ileje', 'Mbozi', 'Momba', 'Songwe'],
        'Tabora': ['Tabora Municipal', 'Igunga', 'Kaliua', 'Nzega', 'Sikonge', 'Urambo', 'Uyui'],
        'Tanga': ['Tanga City', 'Handeni', 'Kilindi', 'Korogwe', 'Lushoto', 'Mkinga', 'Muheza', 'Pangani'],
        'Zanzibar North': ['North A', 'North B'],
        'Zanzibar South': ['Central', 'South'],
        'Zanzibar Urban/West': ['Urban', 'West A', 'West B'],
    },

    # UGA (4 regions)
    "UGA": {
        'Central': ['Kampala', 'Wakiso', 'Mukono', 'Masaka', 'Buikwe', 'Buvuma', 'Gomba', 'Kalangala', 'Kalungu', 'Kayunga', 'Kiboga', 'Kyankwanzi', 'Luwero', 'Lwengo', 'Lyantonde', 'Mityana', 'Mpigi', 'Mubende', 'Nakaseke', 'Nakasongola', 'Rakai', 'Sembabule', 'Kyotera', 'Kasanda'],
        'Eastern': ['Jinja', 'Mbale', 'Iganga', 'Soroti', 'Tororo', 'Bugiri', 'Busia', 'Butaleja', 'Butebo', 'Buyende', 'Kaliro', 'Kamuli', 'Kapchorwa', 'Katakwi', 'Kibuku', 'Kumi', 'Kween', 'Luuka', 'Manafwa', 'Mayuge', 'Namayingo', 'Namisindwa', 'Namutumba', 'Ngora', 'Pallisa', 'Serere', 'Sironko', 'Bukwo', 'Bulambuli', 'Bugweri', 'Kapelebyong'],
        'Northern': ['Gulu', 'Arua', 'Lira', 'Kitgum', 'Abim', 'Adjumani', 'Agago', 'Alebtong', 'Amolatar', 'Amudat', 'Amuru', 'Apac', 'Dokolo', 'Kaabong', 'Koboko', 'Kole', 'Kotido', 'Lamwo', 'Maracha', 'Moroto', 'Moyo', 'Nakapiripirit', 'Nabilatuk', 'Nebbi', 'Nwoya', 'Omoro', 'Otuke', 'Oyam', 'Pader', 'Pakwach', 'Yumbe', 'Zombo', 'Madi-Okollo', 'Kwania', 'Karenga'],
        'Western': ['Mbarara', 'Fort Portal', 'Kabale', 'Kasese', 'Buhweju', 'Buliisa', 'Bundibugyo', 'Bushenyi', 'Hoima', 'Ibanda', 'Isingiro', 'Kagadi', 'Kakumiro', 'Kamwenge', 'Kanungu', 'Kibaale', 'Kiruhura', 'Kiryandongo', 'Kisoro', 'Kyegegwa', 'Kyenjojo', 'Masindi', 'Mitooma', 'Ntoroko', 'Ntungamo', 'Rubanda', 'Rubirizi', 'Rukiga', 'Rukungiri', 'Sheema', 'Kikuube', 'Kitagwenda', 'Rwampara'],
    },

    # ZAF (9 regions)
    "ZAF": {
        'Eastern Cape': ['Buffalo City', 'Nelson Mandela Bay', 'Sarah Baartman', 'Amathole', 'Chris Hani', 'Joe Gqabi', 'OR Tambo', 'Alfred Nzo'],
        'Free State': ['Mangaung', 'Fezile Dabi', 'Lejweleputswa', 'Thabo Mofutsanyana', 'Xhariep'],
        'Gauteng': ['City of Johannesburg', 'City of Tshwane', 'Ekurhuleni', 'Sedibeng', 'West Rand'],
        'KwaZulu-Natal': ['eThekwini', 'uMgungundlovu', 'Ugu', 'uThukela', 'uMzinyathi', 'Amajuba', 'Zululand', 'uMkhanyakude', 'King Cetshwayo', 'iLembe', 'Harry Gwala'],
        'Limpopo': ['Capricorn', 'Mopani', 'Sekhukhune', 'Vhembe', 'Waterberg'],
        'Mpumalanga': ['Ehlanzeni', 'Gert Sibande', 'Nkangala'],
        'North West': ['Bojanala Platinum', 'Dr Kenneth Kaunda', 'Dr Ruth Segomotsi Mompati', 'Ngaka Modiri Molema'],
        'Northern Cape': ['Frances Baard', 'John Taolo Gaetsewe', 'Namakwa', 'Pixley ka Seme', 'ZF Mgcawu'],
        'Western Cape': ['City of Cape Town', 'Cape Winelands', 'Garden Route', 'Overberg', 'West Coast', 'Central Karoo'],
    },

    # ZMB (10 regions)
    "ZMB": {
        'Central': ['Kabwe', 'Chibombo', 'Kapiri Mposhi', 'Mkushi', 'Mumbwa', 'Serenje', 'Chisamba', 'Luano', 'Ngabwe', 'Itezhi-Tezhi'],
        'Copperbelt': ['Ndola', 'Kitwe', 'Chingola', 'Mufulira', 'Luanshya', 'Kalulushi', 'Chililabombwe', 'Lufwanyama', 'Masaiti', 'Mpongwe'],
        'Eastern': ['Chipata', 'Lundazi', 'Petauke', 'Katete', 'Nyimba', 'Chadiza', 'Mambwe', 'Sinda', 'Vubwi', 'Chasefu', 'Lumezi', 'Kasenengwa', 'Lusangazi'],
        'Luapula': ['Mansa', 'Kawambwa', 'Nchelenge', 'Samfya', 'Mwense', 'Chienge', 'Milenge', 'Chembe', 'Chipili', 'Mwansabombwe', 'Chifunabuli', 'Lunga'],
        'Lusaka': ['Lusaka', 'Chongwe', 'Kafue', 'Chilanga', 'Chirundu', 'Luangwa', 'Shibuyunji'],
        'Muchinga': ['Chinsali', 'Mpika', 'Isoka', 'Nakonde', 'Mafinga', "Shiwang'andu", 'Chama', 'Lavushimanda', 'Kanchibiya'],
        'North-Western': ['Solwezi', 'Kasempa', 'Mwinilunga', 'Zambezi', 'Kabompo', 'Chavuma', 'Mufumbwe', 'Ikelenge', 'Manyinga', 'Kalumbila', 'Mushindamo'],
        'Northern': ['Kasama', 'Mbala', 'Mporokoso', 'Luwingu', 'Mpulungu', 'Kaputa', 'Mungwi', 'Chilubi', 'Lunte', 'Lupososhi', 'Senga Hill'],
        'Southern': ['Livingstone', 'Choma', 'Mazabuka', 'Monze', 'Kalomo', 'Sinazongwe', 'Siavonga', 'Gwembe', 'Namwala', 'Zimba', 'Chikankata', 'Kazungula'],
        'Western': ['Mongu', 'Kaoma', 'Senanga', 'Sesheke', 'Kalabo', 'Lukulu', "Shang'ombo", 'Mwandi', 'Nalolo', 'Sioma', 'Sikongo', 'Luampa', 'Mitete', 'Nkeyema'],
    },

    # ZWE (10 regions)
    "ZWE": {
        'Bulawayo': ['Bulawayo Urban'],
        'Harare': ['Harare Urban', 'Harare Rural', 'Chitungwiza', 'Epworth'],
        'Manicaland': ['Mutare Urban', 'Mutare Rural', 'Buhera', 'Chimanimani', 'Chipinge', 'Makoni', 'Mutasa', 'Nyanga'],
        'Mashonaland Central': ['Bindura', 'Guruve', 'Mazowe', 'Mt Darwin', 'Muzarabani', 'Rushinga', 'Shamva', 'Mbire'],
        'Mashonaland East': ['Marondera', 'Goromonzi', 'Murehwa', 'Mutoko', 'Wedza', 'Chikomba', 'Mudzi', 'Seke', 'Uzumba-Maramba-Pfungwe'],
        'Mashonaland West': ['Chinhoyi', 'Chegutu', 'Kadoma', 'Kariba', 'Makonde', 'Mhondoro-Ngezi', 'Sanyati', 'Zvimba', 'Hurungwe'],
        'Masvingo': ['Masvingo Urban', 'Masvingo Rural', 'Bikita', 'Chiredzi', 'Chivi', 'Gutu', 'Mwenezi', 'Zaka'],
        'Matabeleland North': ['Binga', 'Bubi', 'Hwange', 'Lupane', 'Nkayi', 'Tsholotsho', 'Umguza'],
        'Matabeleland South': ['Beitbridge', 'Bulilima', 'Gwanda', 'Insiza', 'Mangwe', 'Matobo', 'Umzingwane'],
        'Midlands': ['Gweru', 'Kwekwe', 'Gokwe North', 'Gokwe South', 'Chirumhanzu', 'Mberengwa', 'Shurugwi', 'Zvishavane'],
    },

}
