# Generated by Django 5.2.17 on 2026-10-06 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auditevent_detail'),
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('forming', 'Forming'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('lead_name', models.CharField(blank=True, max_length=150)),
                ('lead_email', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('tier', models.PositiveSmallIntegerField(default=5, help_text='1: Global/Network, 2: Regional, 3: Country, 4: Chapter/Local, 5: Member')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('export', 'Data Export'), ('rectification', 'Data Rectification'), ('erasure', 'Data Erasure / Deletion'), ('restriction', 'Restriction of Processing')], max_length=32)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='submitted', max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('export_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_requests', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=8)),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('font_size', models.CharField(choices=[('standard', 'Standard'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='standard', max_length=16)),
                ('email_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('activity_digest', models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('none', 'None')], default='daily', max_length=16)),
                ('active_network', models.CharField(blank=True, max_length=8)),
                ('active_country', models.CharField(blank=True, max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network', models.CharField(blank=True, max_length=8)),
                ('country', models.CharField(blank=True, max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('work_queue', 'Work Queue'), ('security', 'Security'), ('system', 'System'), ('privacy', 'Privacy Request'), ('activity', 'Activity')], default='system', max_length=32)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(choices=[('delivered', 'Delivered'), ('failed', 'Failed'), ('pending', 'Pending')], default='delivered', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'is_read'], name='foundation__account_862a57_idx'), models.Index(fields=['account', 'network'], name='foundation__account_08f4dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('review', 'Review'), ('membership', 'Membership'), ('approval', 'Approval'), ('incident', 'Incident'), ('privacy', 'Privacy Request'), ('onboarding', 'Onboarding'), ('general', 'General')], default='general', max_length=32)),
                ('network', models.CharField(choices=[('WGMN', 'WGMN'), ('WNNN', 'WNNN')], max_length=8)),
                ('country', models.CharField(max_length=8)),
                ('required_role', models.CharField(default='member', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=24)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=16)),
                ('confidential', models.BooleanField(default=False)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_items', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_items', to='accounts.account')),
                ('leadership_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='foundation.leadershiplevel')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['network', 'country', 'status'], name='foundation__network_dff73b_idx'), models.Index(fields=['assigned_to', 'status'], name='foundation__assigne_dd0efe_idx')],
            },
        ),
    ]
