# Generated by Django 5.2.17 on 2026-10-06 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auditevent_detail'),
        ('foundation', '0002_countryhub_leadershiplevel_privacyrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('network', models.CharField(choices=[('WGMN', 'WGMN'), ('WNNN', 'WNNN')], max_length=8)),
                ('country', models.CharField(max_length=8)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('forming', 'Forming'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('lead_name', models.CharField(blank=True, max_length=150)),
                ('lead_email', models.CharField(blank=True, max_length=150)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['network', 'country'], name='foundation__network_8e278e_idx'), models.Index(fields=['code'], name='foundation__code_0800a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sender_name', models.CharField(default='Headquarters', max_length=150)),
                ('network', models.CharField(choices=[('WGMN', 'WGMN'), ('WNNN', 'WNNN'), ('ALL', 'All Networks')], default='ALL', max_length=8)),
                ('country', models.CharField(default='ALL', max_length=8)),
                ('target_role', models.CharField(default='all', max_length=48)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['network', 'country', 'target_role'], name='foundation__network_0bcdbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('executive_summary', 'Executive Summary'), ('operational_pulse', 'Operational Pulse'), ('country_health', 'Country Health'), ('chapter_assessment', 'Chapter Assessment'), ('onboarding_throughput', 'Onboarding Throughput'), ('compliance_audit', 'Compliance Audit')], max_length=48)),
                ('network', models.CharField(choices=[('WGMN', 'WGMN'), ('WNNN', 'WNNN'), ('ALL', 'All Networks')], default='ALL', max_length=8)),
                ('country', models.CharField(default='ALL', max_length=8)),
                ('geography', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(max_length=64)),
                ('summary', models.TextField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='published', max_length=24)),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['network', 'country', 'status'], name='foundation__network_afbf21_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=48)),
                ('network', models.CharField(choices=[('WGMN', 'WGMN'), ('WNNN', 'WNNN')], max_length=8)),
                ('country', models.CharField(max_length=8)),
                ('geography', models.CharField(blank=True, max_length=100)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['network', 'country'], name='foundation__network_7ee988_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('category', models.CharField(choices=[('governance', 'Governance'), ('operations', 'Operations'), ('compliance', 'Compliance'), ('verification', 'Verification'), ('chapter', 'Chapter')], default='operations', max_length=32)),
                ('network', models.CharField(choices=[('WGMN', 'WGMN'), ('WNNN', 'WNNN'), ('ALL', 'All Networks')], default='ALL', max_length=8)),
                ('country', models.CharField(default='ALL', max_length=8)),
                ('geography', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ManyToManyField(blank=True, related_name='acknowledged_alerts', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['network', 'country', 'is_active'], name='foundation__network_2d368b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('meeting_type', models.CharField(choices=[('strategic_hq', 'Strategic HQ Council'), ('operational_sync', 'Operational Sync'), ('country_assembly', 'Country Assembly'), ('chapter_meetup', 'Chapter Meetup'), ('orientation', 'Candidate Orientation'), ('community_open', 'Community Open Session')], max_length=48)),
                ('network', models.CharField(choices=[('WGMN', 'WGMN'), ('WNNN', 'WNNN'), ('ALL', 'All Networks')], default='ALL', max_length=8)),
                ('country', models.CharField(default='ALL', max_length=8)),
                ('geography', models.CharField(blank=True, max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('attendees_count', models.PositiveIntegerField(default=0)),
                ('target_role', models.CharField(default='all', max_length=48)),
                ('organizer_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rsvp_accounts', models.ManyToManyField(blank=True, related_name='rsvpd_meetings', to='accounts.account')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['network', 'country', 'scheduled_at'], name='foundation__network_c9acd1_idx')],
            },
        ),
    ]
