# Generated by Django 5.2.17 on 2026-10-08 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_countrycatalogue_dataimprovementflag_and_more'),
        ('foundation', '0003_chapter_communication_dashboardreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacyrequest',
            name='current_step',
            field=models.CharField(default='Identity check required', max_length=64),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='decision',
            field=models.CharField(default='More information needed', max_length=64),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='identity_check_status',
            field=models.CharField(default='Not checked', max_length=32),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='next_action',
            field=models.CharField(default='Confirm through the approved verification route', max_length=128),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='reason_and_retention',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='reference',
            field=models.CharField(default='PR-DEMO-01', max_length=32),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='safe_reply_route',
            field=models.CharField(default='Reply in my account', max_length=64),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='reminder_preference',
            field=models.CharField(choices=[('inside_wdos', 'Keep reminders inside WDOS'), ('browser', 'Send browser notifications'), ('none', 'Do not send reminders')], default='inside_wdos', max_length=64),
        ),
        migrations.AlterField(
            model_name='privacyrequest',
            name='request_type',
            field=models.CharField(default='Correct my information', max_length=64),
        ),
        migrations.AlterField(
            model_name='privacyrequest',
            name='status',
            field=models.CharField(default='Waiting for review', max_length=32),
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('device_name', models.CharField(default='This device', max_length=128)),
                ('browser_info', models.CharField(default='Chrome · Lagos', max_length=128)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=64)),
                ('is_current', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to='accounts.account')),
            ],
            options={
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='NetworkTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_relationship', models.CharField(default='WNNN membership', max_length=128)),
                ('requested_transition', models.CharField(default='WGMN membership review', max_length=128)),
                ('age_evidence_method', models.CharField(default='Approved re-attestation', max_length=128)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(default='in_progress', max_length=32)),
                ('step', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_transitions', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
