# Generated by Django 5.2.17 on 2026-09-22 09:37

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Throttle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('suspended', 'suspended')], default='pending', max_length=16)),
                ('verified_at', models.DateTimeField(null=True)),
                ('security_version', models.PositiveIntegerField(default=1)),
                ('mfa_secret', models.TextField(blank=True)),
                ('mfa_pending_secret', models.TextField(blank=True)),
                ('mfa_pending_until', models.DateTimeField(null=True)),
                ('mfa_last_counter', models.BigIntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('network', models.CharField(max_length=32)),
                ('geography', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='ActionToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('verify', 'verify'), ('reset', 'reset')], max_length=12)),
                ('digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='EmailIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_payload', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'pending'), ('blocked', 'blocked'), ('sending', 'sending'), ('accepted', 'accepted'), ('failed', 'failed'), ('unknown', 'unknown'), ('expired', 'expired')], default='pending', max_length=16)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.actiontoken')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('used_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='account_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'active', 'suspended'])), name='account_valid_status'),
        ),
    ]
