# Generated by Django 5.2.17 on 2026-09-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailintent_expires_at_emailintent_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('next_step', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(default='draft', max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('next_step__gte', 1), ('next_step__lte', 8)), name='onboarding_valid_step'), models.CheckConstraint(condition=models.Q(('state__in', ['draft', 'review_needed', 'accepted'])), name='onboarding_valid_state')],
            },
        ),
    ]
