# Generated by Django 5.2.17 on 2026-09-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_onboarding_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdraft',
            name='submission_revision',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='onboardingdraft',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='OnboardingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('version', models.CharField(max_length=100)),
                ('notice', models.TextField()),
                ('digest', models.CharField(max_length=64)),
                ('approval_reference', models.CharField(max_length=500)),
                ('privacy_ack', models.BooleanField()),
                ('optional_updates', models.BooleanField(default=False)),
                ('channel', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='accounts.onboardingdraft')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('draft', 'revision'), name='onboarding_consent_once')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=32)),
                ('revision', models.PositiveIntegerField()),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='accounts.onboardingdraft')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('draft', 'revision', 'event'), name='onboarding_event_once')],
            },
        ),
    ]
