# Generated by Django 5.2.17 on 2026-09-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_onboarding_consent_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=8)),
                ('home', models.JSONField()),
                ('policy_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.onboardingconsent')),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membership', to='accounts.onboardingdraft')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('network__in', ['WGMN', 'WNNN'])), name='membership_explicit_network')],
            },
        ),
    ]
