# Generated by Django 5.2.17 on 2026-09-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_onboarding_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdraft',
            name='photo',
            field=models.BinaryField(blank=True, default=bytes),
        ),
    ]
