# Generated by Django 5.2.17 on 2026-10-07 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auditevent_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCatalogue',
            fields=[
                ('iso3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('iso2', models.CharField(db_index=True, max_length=2, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('admin1_label', models.CharField(max_length=100)),
                ('admin2_label', models.CharField(max_length=100)),
                ('level2_reliable', models.BooleanField(default=False)),
                ('source', models.CharField(default='geoBoundaries gbOpen', max_length=100)),
                ('source_version', models.CharField(default='gbOpen-v4.0', max_length=50)),
                ('last_verified_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Country Catalogue',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataImprovementFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_iso3', models.CharField(max_length=3)),
                ('region_id', models.CharField(blank=True, max_length=64)),
                ('region_name', models.CharField(blank=True, max_length=150)),
                ('unlisted_subdivision', models.CharField(max_length=150)),
                ('unit_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('catalogued', 'Added to Catalogue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geography_flags', to='accounts.account')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_improvement_flags', to='accounts.onboardingdraft')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeDivision',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')], db_index=True)),
                ('display_name', models.CharField(db_index=True, max_length=150)),
                ('local_unit_type', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('source_version', models.CharField(max_length=50)),
                ('last_verified_date', models.DateField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.administrativedivision')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='accounts.countrycatalogue')),
            ],
            options={
                'ordering': ['display_name'],
                'constraints': [models.UniqueConstraint(fields=('country', 'parent', 'display_name'), name='unique_division_per_parent')],
            },
        ),
    ]
